### ISSUE TITLE
Error when generating ship

### ISSUE THREAD

**Issue by oscitare** [LemADEC/WarpDrive#101]
When the "/generate ship" command is used, it returns "An unknown error occurred when attempting to perform this command," below is the text found in the log:

```
[16:43:26] [Server thread/INFO] [WarpDrive]: /generate: generating NPC ship at 137, 84, 294
[16:43:27] [Server thread/ERROR]: Couldn't process command: 'generate ship'
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) ~[add.class:?]
    at cr0s.warpdrive.world.WorldGenSmallShip.getRandomBonus(WorldGenSmallShip.java:635) ~[WorldGenSmallShip.class:?]
    at cr0s.warpdrive.world.WorldGenSmallShip.fillChestWithBonuses(WorldGenSmallShip.java:621) ~[WorldGenSmallShip.class:?]
    at cr0s.warpdrive.world.WorldGenSmallShip.func_76484_a(WorldGenSmallShip.java:191) ~[WorldGenSmallShip.class:?]
    at cr0s.warpdrive.command.CommandGenerate.func_71515_b(CommandGenerate.java:58) ~[CommandGenerate.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[16:43:27] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
```

**Comment by LemADEC** [comment]
Which mods do you have installed in your setup?

**Comment by oscitare** [comment]
Mods: `WarpDrive-1.7.10-1.3.10.jar`, and [VoxelMap](http://minecraft.curseforge.com/projects/voxelmap) (which uses [LiteLoader](http://www.liteloader.com/)).

**Comment by LemADEC** [comment]
No IC2 or EnderIO or anything else?

**Comment by oscitare** [comment]
Are those necessary prerequisites? If so, reply back and I'll try the mod with those as well.

**Comment by LemADEC** [comment]
You need at least one energy mod providing EU or RF, and one computer mod (ComputerCraft or OpenComputers).
In your case, it might be a bug related to IC2 dependency, not sure yet.

**Comment by oscitare** [comment]
Okay, it worked now... Thanks for your help!
