### ISSUE TITLE
Laser medium texture ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Cr0s** [LemADEC/WarpDrive#102]
When I started to charging LaserMedium block beneath the mining laser

`
java.lang.ArrayIndexOutOfBoundsException: 10
    at cr0s.warpdrive.block.BlockLaserMedium.func_149691_a(BlockLaserMedium.java:45)
    at net.minecraft.block.Block.func_149673_e(Block.java:556)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4800)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by LemADEC** [comment]
Laser medium metadata was downscaled from 0-10 to 0-7, I can see this bug happening only when loading an old map, is that the case here?

**Comment by Cr0s** [comment]
Nope, this happened with just created map when I trying to charge Laser medium for mining laser. I created a fix with range checking of metadata and pushed it as pull-request.

**Comment by LemADEC** [comment]
then we have another bug somewhere

**Comment by Cr0s** [comment]
Obviously, in TileEntity

**Comment by LemADEC** [comment]
Metadata is supposed to be set here:
https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/block/TileEntityLaserMedium.java#L27
can't see why it would go to 10 from that, and parent classes aren't supposed to change metadata, so it's somewhere else...
