### ISSUE TITLE
ComputerCraft scripts not loading in dev space

### ISSUE THREAD

**Issue by Nommy228** [LemADEC/WarpDrive#116]
When connecting Ship Controller to Advanced Computer, I get an error in 

```
TileEntityAbstractInterfaced::attach

on line

computer.mount("/" + peripheralName, ComputerCraftAPI.createResourceMount(WarpDrive.class, WarpDrive.MODID.toLowerCase(), "lua.ComputerCraft/" + peripheralName));

this.getClass().getName() == cr0s.warpdrive.block.movement.TileEntityShipController

exception:

t.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:709) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
    at dan200.computercraft.core.filesystem.FileSystem.mount(FileSystem.java:329) ~[FileSystem.class:?]
    at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.mount(PeripheralAPI.java:142) ~[PeripheralAPI$PeripheralWrapper.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.mount(TileCable.java:935) ~[TileCable$RemotePeripheralWrapper.class:?]
    at cr0s.warpdrive.block.TileEntityAbstractInterfaced.attach(TileEntityAbstractInterfaced.java:250) ~[TileEntityAbstractInterfaced.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.attach(TileCable.java:900) ~[TileCable$RemotePeripheralWrapper.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.attachPeripheral(TileCable.java:735) ~[TileCable.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:1032) ~[TileCable.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.updateEntity(TileCable.java:659) ~[TileCable.class:?]
    at net.minecraft.world.World.updateEntities(World.java:2160) ~[World.class:?]
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703) ~[MinecraftServer.class:?]
    ... 4 more
```

**Comment by LemADEC** [comment]
I'll need the full crash logs

**Comment by Nommy228** [comment]
[08:34:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:709) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
    at dan200.computercraft.core.filesystem.FileSystem.mount(FileSystem.java:329) ~[FileSystem.class:?]
    at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.mount(PeripheralAPI.java:142) ~[PeripheralAPI$PeripheralWrapper.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.mount(TileCable.java:935) ~[TileCable$RemotePeripheralWrapper.class:?]
    at cr0s.warpdrive.block.TileEntityAbstractInterfaced.attach(TileEntityAbstractInterfaced.java:250) ~[TileEntityAbstractInterfaced.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.attach(TileCable.java:900) ~[TileCable$RemotePeripheralWrapper.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.attachPeripheral(TileCable.java:735) ~[TileCable.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:1032) ~[TileCable.class:?]
    at dan200.computercraft.shared.peripheral.modem.TileCable.updateEntity(TileCable.java:659) ~[TileCable.class:?]
    at net.minecraft.world.World.updateEntities(World.java:2160) ~[World.class:?]
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703) ~[MinecraftServer.class:?]
    ... 4 more
[08:34:52] [Server thread/ERROR]: This crash report has been saved to: D:\proj\WarpDrive\eclipse.\crash-reports\crash-2015-12-14_08.34.52-server.txt
[08:34:52] [Server thread/INFO]: Stopping server
[08:34:52] [Server thread/INFO]: Saving players
[08:34:52] [Server thread/INFO]: Saving worlds
[08:34:52] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[08:34:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 14.12.15 8:34
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at dan200.computercraft.core.filesystem.FileSystem.mount(FileSystem.java:329)
    at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.mount(PeripheralAPI.java:142)
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.mount(TileCable.java:935)
    at cr0s.warpdrive.block.TileEntityAbstractInterfaced.attach(TileEntityAbstractInterfaced.java:250)
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.attach(TileCable.java:900)
    at dan200.computercraft.shared.peripheral.modem.TileCable.attachPeripheral(TileCable.java:735)
    at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:1032)
    at dan200.computercraft.shared.peripheral.modem.TileCable.updateEntity(TileCable.java:659)
    at net.minecraft.world.World.updateEntities(World.java:2160)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at dan200.computercraft.core.filesystem.FileSystem.mount(FileSystem.java:329)
    at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.mount(PeripheralAPI.java:142)
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.mount(TileCable.java:935)
    at cr0s.warpdrive.block.TileEntityAbstractInterfaced.attach(TileEntityAbstractInterfaced.java:250)
    at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.attach(TileCable.java:900)
    at dan200.computercraft.shared.peripheral.modem.TileCable.attachPeripheral(TileCable.java:735)
    at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:1032)
    at dan200.computercraft.shared.peripheral.modem.TileCable.updateEntity(TileCable.java:659)

-- Block entity being ticked --
Details:
    Name: wiredmodem // dan200.computercraft.shared.peripheral.modem.TileCable
    Block type: ID #412 (tile.computercraft:cable // dan200.computercraft.shared.peripheral.common.BlockCable)
    Block data value: 11 / 0xB / 0b1011
    Block location: World: (-79,68,210), Chunk: (at 1,4,2 in -5,13; contains blocks -80,0,208 to -65,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #412 (tile.computercraft:cable // dan200.computercraft.shared.peripheral.common.BlockCable)
    Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:2160)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['Player542'/299, l='New World', x=-79,34, y=68,00, z=211,04]]
    Chunk stats: ServerChunkCache: 721 Drop: 0
    Level seed: 6119978648608953777
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-61,64,203), Chunk: (at 3,4,11 in -4,12; contains blocks -64,0,192 to -49,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 46602 game time, 1086 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 135559 (now: false), thunder time: 50467 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 527210928 bytes (502 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   WarpDriveCore{@version@} [WarpDriveCore](minecraft.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303-dev.jar) 
    UCHIJAAAA   ComputerCraft{1.75} [ComputerCraft](ComputerCraft1.75.jar) 
    UCHIJAAAA   IC2{2.2.808-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.808-experimental-dev.jar) 
    UCHIJAAAA   WarpDrive{@version@} [WarpDrive](bin) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Player542'/299, l='New World', x=-79,34, y=68,00, z=211,04]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
[08:34:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:393]: #@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2015-12-14_08.34.52-server.txt
[08:34:52] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[08:34:52] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[08:34:52] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[08:34:52] [Server thread/INFO]: Saving chunks for level 'New World'/Hyperspace
[08:34:52] [Server thread/INFO]: Saving chunks for level 'New World'/Space
[08:34:52] [Server thread/INFO] [FML]: Unloading dimension 0
[08:34:52] [Server thread/INFO] [FML]: Unloading dimension -1
[08:34:52] [Server thread/INFO] [FML]: Unloading dimension 1
[08:34:52] [Server thread/INFO] [FML]: Unloading dimension -3
[08:34:52] [Server thread/INFO] [FML]: Unloading dimension -2
[08:34:52] [Server thread/INFO] [FML]: Applying holder lookups
[08:34:52] [Server thread/INFO] [FML]: Holder lookups applied
[08:34:52] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[08:34:52] [Client thread/INFO] [FML]: Server terminated.

**Comment by Nommy228** [comment]
What do I do:
1. Place an advanced computer
2. Open it so it will boot
3. Place a modem on Advanced Computer
4. Place a modem on Ship Controller
5. Connect them
6. Turn Computer modem on
7. Turn Controller modem on
8. KABOOM

Alternatively, if I place all modems and turn them on without step 2, then when I am trying to open computer after all is set up  it just shows empty screen and won't boot CraftOS

**Comment by LemADEC** [comment]
Looks like you've recompiled the mod without adding resources. You should use the gradle script that comes with the source instead of building it by hand.

**Comment by Nommy228** [comment]
That's what i did. Everything else works like a charm.
I can give TeamView desktop control or something to debug remotely

Please provide any contacts outside github (skype, vk / facebook) as I am willing to coordinate & contribute

**Comment by LemADEC** [comment]
You can reach me on the community TeamSpeak server ts.funsquaregames.com

**Comment by LemADEC** [comment]
From within a debug environment like Eclipse, the LUA scripts can't be preloaded because resources are handled completely differently. We would need some complicated dedicated code just for that, so it's not really worth it.

To compile the mod, open command terminal / console, go to the mod repository root folder:
- on first time usage, you need to type "gradlew setupDecompWorkspace" (and wait).
- to recompile after a change, type "gradlew build".
  The output will be in the "./build/libs" folder.

**Comment by LemADEC** [comment]
OpenComputers is able to load scripts just fine.

**Comment by LemADEC** [comment]
There's no proper CC for dev space, won't fix until that changes
