### ISSUE TITLE
AdvancedSolarPanels Crash on jump

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#141]
Anything other than the default solar panel on ships for power is resulting the below server crash for me on jump

```
java.lang.NullPointerException: Ticking block entity
        at ic2.core.energy.EnergyNetLocal.removeTileFromGrids(EnergyNetLocal.java:645)
        at ic2.core.energy.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:249)
        at ic2.core.energy.EventHandler.onEnergyTileUnload(EventHandler.java:38)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at advsolar.common.tiles.TileEntitySolarPanel.onUnloaded(TileEntitySolarPanel.java:137)
        at advsolar.common.tiles.TileEntitySolarPanel.func_145845_h(TileEntitySolarPanel.java:183)
        at net.minecraft.world.World.func_72939_s(World.java:2529)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:628)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at ic2.core.energy.EnergyNetLocal.removeTileFromGrids(EnergyNetLocal.java:645)
        at ic2.core.energy.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:249)
        at ic2.core.energy.EventHandler.onEnergyTileUnload(EventHandler.java:38)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at advsolar.common.tiles.TileEntitySolarPanel.onUnloaded(TileEntitySolarPanel.java:137)
        at advsolar.common.tiles.TileEntitySolarPanel.func_145845_h(TileEntitySolarPanel.java:183)

-- Block entity being ticked --
Details:
        Name: Ultimate Hybrid Solar Panel // advsolar.common.tiles.TileEntityUltimateSolarPanel
        Block type: ID #231 (tile.null // advsolar.common.blocks.BlockAdvSolarPanel)
        Block data value: 2 / 0x2 / 0b0010
        Block location: World: (-153,16,28), Chunk: (at 7,1,12 in -10,1; contains blocks -160,0,16 to -145,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)

```

**Comment by LemADEC** [comment]
I'll need the full crash logs for that one

**Comment by DraksterAU** [comment]
This doesn't occur in the official version. Sorry my bad.

**Comment by StargateMC** [comment]
This occurs with the latest IC2 Experimental (Latest) + Advanced Solar Panels v3.5.1 (Latest), my custom build wasn't at fault.
This causes corrupt worlds. Lucky I backup 8 times a day.
Will get logs asap.

**Comment by LemADEC** [comment]
Can't reproduce in SSP while jumping between overworld and space with
AdvancedSolarPanel-1.7.10-3.5.1
ComputerCraft1.75
industrialcraft-2-2.2.765-experimental
WarpDrive-1.7.10-1.3.18-dev.-
1.7.10-Forge10.13.4.1566-1.7.10

Updated with industrialcraft-2-2.2.815-experimental => still can't reproduce

Updated with WarpDrive-1.7.10-1.3.19-dev.- => still can't reproduce

**Comment by StargateMC** [comment]
This was done in multiplayer @lemadec.
Not SSP. It works beautifully in SSP.

**Comment by LemADEC** [comment]
no logs, no issue
