### ISSUE TITLE
MC1.6.4, issues with version 1.2.0

### ISSUE THREAD

**Issue by justjosephbird** [LemADEC/WarpDrive#145]
I decided to build a U.S.S Enterprise in Minecraft using this mod, so I built a awesome huge one. So I added the dimensions which I made sure were accurate, I set the warp data but It didn't jump! It thought it had though because it still used the energy. I tried multiple times. Please help!

**Comment by CaptainMegavolt** [comment]
How far did you tell it to jump? There's a bug (i think it hasn't been
fixed yet anyway) where big ships will 'hit' themself when trying to jump.

_--Marvin_Megavolt_

**Comment by justjosephbird** [comment]
I told it to jump 336 blocks forward.

**Comment by CaptainMegavolt** [comment]
And how long was your ship?

_--Marvin_Megavolt_

**Comment by justjosephbird** [comment]
332 blocks long.

**Comment by CaptainMegavolt** [comment]
In that case, it almost certainly wasn't the ship colliding with itself. To
be honest, I've never seen a problem like this before.

_--Marvin_Megavolt_

**Comment by LemADEC** [comment]
What version of the mod are you using?
What was the message reported by the guide?

**Comment by justjosephbird** [comment]
It is version 1.2.0
What do you mean message reported by guide?

**Comment by justjosephbird** [comment]
I just tried again, this time it still didn't jump but it didn't use the power either.
But it still made the sound.

**Comment by LemADEC** [comment]
Version 1.2.0 is highly bugged, use 1.2.7.0 instead for Minecraft 1.6.4.
Or switch to Minecraft 1.7.10 and use latest beta.

**Comment by justjosephbird** [comment]
Okay.

**Comment by justjosephbird** [comment]
I got the new version, and now when I get on it crashes.
Here is the crash report:

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 3/21/16 3:53 PM
Description: Initializing game

java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheralProvider
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.api.peripheral.IPeripheralProvider
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 34 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 36 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 139653464 bytes (133 MB) / 223121408 bytes (212 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 42 mods loaded, 42 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
    FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed
    Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed
    AppliedEnergistics-Core{rv13.c} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed
    OpenModsCore{0.4} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
    RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) Unloaded->Constructed
    WarpDriveCore{1.0.0.1} [WarpDriveCore] (minecraft.jar) Unloaded->Constructed
    FamiliarsAPI{1.6.4} [Familiars API] (Familiars_API_1.6.4a.zip) Unloaded->Constructed
    IGWMod{1.0.1} [In-Game Wiki Mod] (IGW-Mod-1.0.1) Unloaded->Constructed
    DamageIndicatorsMod{2.9.1.5} [Damage Indicators] (1.6.4_DamageIndicatorsv2.9.1.5.zip) Unloaded->Constructed
    mod_ZanMinimap{0.9.4} [Zan's Minimap] (14158977062_ZansMinimap1.6.4.zip) Unloaded->Constructed
    AppliedEnergistics{rv13.c} [Applied Energistics] (appeng-rv13-c-mc162.jar) Unloaded->Constructed
    BetterDungeons{2.4} [Chocolate quest] (BetterDungeons207.zip) Unloaded->Constructed
    BetterGrassAndLeavesMod{1.6.4.D} [Better Grass & Leaves Mod] (BetterGrassAndLeavesMod[v1.6.4.D].jar) Unloaded->Constructed
    CarpentersBlocks{v1.9.7} [Carpenter's Blocks] (Carpenters_Blocks_v1.9.7_MC_1.6+.zip) Unloaded->Constructed
    CoFHCore{2.0.0.2} [CoFH Core] (CoFH-Core-1.6.4.jar) Unloaded->Constructed
    CoFHLoot{2.0.0.2} [CoFH Loot] (CoFH-Core-1.6.4.jar) Unloaded->Constructed
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade] (CoFH-Core-1.6.4.jar) Unloaded->Constructed
    CoFHSocial{2.0.0.2} [CoFH Social] (CoFH-Core-1.6.4.jar) Unloaded->Constructed
    CoFHWorld{2.0.0.2} [CoFH World] (CoFH-Core-1.6.4.jar) Unloaded->Constructed
    ComputerCraft{1.58} [ComputerCraft] (ComputerCraft1.58.zip) Unloaded->Constructed
    CCTurtle{1.58} [ComputerCraft Turtles] (ComputerCraft1.58.zip) Unloaded->Constructed
    dimdoors{1.6.2R2.1.1RC1} [Dimensional Doors] (DimensionalDoors-2.1.0-BETA.zip) Unloaded->Constructed
    FamiliarsDefaultMobPack{1.6.4} [Familiars DefaultMobPack] (Familiars_DefaultMobPack_1.6.4a.zip) Unloaded->Constructed
    FamiliarsExtendedFamPack{1.6.4} [Familiars ExtendedFamPack] (Familiars_ExtendedFamPack_1.6.4a.zip) Unloaded->Constructed
    FamiliarsHerobrineFamPack{1.6.4} [Familiars HerobrineFamPack] (Familiars_HerobrineFamPack_1.6.4a.zip) Unloaded->Constructed
    ftfloocraft{0.2, for Minecraft 1.6.4} [Floocraft] (Floocraft-Mod-1.6.4.zip) Unloaded->Constructed
    forgebiosphere{1.0} [forgebiosphere] (forgebiosphere_1.6.4.2.zip) Unloaded->Constructed
    herobrinemod{3.5} [HerobrineMod] (HerobrineMod_1.6.4_3.5_release.zip) Unloaded->Constructed
    iChunUtil{2.4.0} [iChunUtil] (iChunUtil2.4.0.zip) Unloaded->Constructed
    IC2{2.0.357-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.357-experimental.jar) Unloaded->Constructed
    JoypadSplitscreenMod{1.6.4-0.075pre} [Joypad / SplitScreen Mod] (Joypad-Mod-1.6.4.zip) Unloaded->Constructed
    MineChess{1.3.5} [MineChess] (MineChess-1.3.5.zip) Unloaded->Constructed
    Morph{0.3.0} [Morph] (Morph-Beta-0.3.0.zip) Unloaded->Constructed
    NotEnoughCodecs{0.1} [NotEnoughCodecs] (NotEnoughCodecs-0.1.jar) Unloaded->Constructed
    OpenMods{0.4} [OpenMods] (OpenModsLib-0.4b.jar) Unloaded->Constructed
    OpenPeripheralCore{0.3.3} [OpenPeripheralCore] (OpenPeripheralCore-0.3.3.jar) Unloaded->Constructed
    OpenPeripheral{0.1.3} [OpenPeripheralAddons] (OpenPeripheralAddons-0.1.3.jar) Unloaded->Constructed
    OpenBlocks{1.2.7} [OpenBlocks] (OpenBlocks-1.2.7.jar) Unloaded->Constructed
    RedstonePasteMod{1.5.1} [Redstone Paste] (RedstonePasteMod1.5.1.zip) Unloaded->Constructed
    TC{4.2.1_012} [Traincraft] (traincraft-4.2.1_011.jar) Unloaded->Constructed
    WarpDrive{1.2.7.0} [WarpDrive] (WarpDrive-1.6.4-1.2.7.0-advanced.zip) Unloaded
    Launched Version: 1.6.4-Forge9.11.1.1345
    LWJGL: 2.9.0
    OpenGL: Intel Bear Lake B GL version 1.4.0 - Build 7.15.10.5218, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Plaff656s Sci-fi Pack Mk. XVI (1.7.4)(Updated).zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
```

**Comment by LemADEC** [comment]
You need to update at least to the following mods version:
- WarpDriveCore 1.0.0.4
- ComputerCraft 1.63
- industrialcraft-2 2.0.397-experimental
- appeng rv14-finale3
- CoFHCore 2.0.0.5
  and probably a few others from there.

**Comment by justjosephbird** [comment]
Now it doesn't crash on startup, but when I get on my world it crashes. 
Here is the crash report now:

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/21/16 5:22 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: li/cil/oc/api/network/Environment
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
    at java.lang.Class.getConstructor0(Class.java:3067)
    at java.lang.Class.newInstance(Class.java:408)
    at net.minecraft.tileentity.TileEntity.func_70317_c(TileEntity.java:140)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:440)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(AnvilChunkLoader.java:103)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:83)
    at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(ChunkProviderServer.java:182)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:118)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:294)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:90)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:107)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.network.Environment
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 193556816 bytes (184 MB) / 393555968 bytes (375 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 41 mods loaded, 41 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenModsCore{0.4} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WarpDriveCore{1.0.0.3} [WarpDriveCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FamiliarsAPI{1.6.4} [Familiars API] (Familiars_API_1.6.4a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IGWMod{1.0.1} [In-Game Wiki Mod] (IGW-Mod-1.0.1) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    DamageIndicatorsMod{2.9.1.5} [Damage Indicators] (1.6.4_DamageIndicatorsv2.9.1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap] (14158977062_ZansMinimap1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BetterDungeons{2.4} [Chocolate quest] (BetterDungeons207.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BetterGrassAndLeavesMod{1.6.4.D} [Better Grass & Leaves Mod] (BetterGrassAndLeavesMod[v1.6.4.D].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CarpentersBlocks{v1.9.7} [Carpenter's Blocks] (Carpenters_Blocks_v1.9.7_MC_1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    dimdoors{1.6.2R2.1.1RC1} [Dimensional Doors] (DimensionalDoors-2.1.0-BETA.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FamiliarsDefaultMobPack{1.6.4} [Familiars DefaultMobPack] (Familiars_DefaultMobPack_1.6.4a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FamiliarsExtendedFamPack{1.6.4} [Familiars ExtendedFamPack] (Familiars_ExtendedFamPack_1.6.4a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FamiliarsHerobrineFamPack{1.6.4} [Familiars HerobrineFamPack] (Familiars_HerobrineFamPack_1.6.4a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ftfloocraft{0.2, for Minecraft 1.6.4} [Floocraft] (Floocraft-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    forgebiosphere{1.0} [forgebiosphere] (forgebiosphere_1.6.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    herobrinemod{3.5} [HerobrineMod] (HerobrineMod_1.6.4_3.5_release.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    iChunUtil{2.4.0} [iChunUtil] (iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2{2.0.397-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    JoypadSplitscreenMod{1.6.4-0.075pre} [Joypad / SplitScreen Mod] (Joypad-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineChess{1.3.5} [MineChess] (MineChess-1.3.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Morph{0.3.0} [Morph] (Morph-Beta-0.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughCodecs{0.1} [NotEnoughCodecs] (NotEnoughCodecs-0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenMods{0.4} [OpenMods] (OpenModsLib-0.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenPeripheralCore{0.3.3} [OpenPeripheralCore] (OpenPeripheralCore-0.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenPeripheral{0.1.3} [OpenPeripheralAddons] (OpenPeripheralAddons-0.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenBlocks{1.2.7} [OpenBlocks] (OpenBlocks-1.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedstonePasteMod{1.5.1} [Redstone Paste] (RedstonePasteMod1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TC{4.2.1_012} [Traincraft] (traincraft-4.2.1_011.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WarpDrive{1.2.7.0} [WarpDrive] (WarpDrive-1.6.4-1.2.7.0-advanced (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by LemADEC** [comment]
One your mods require OpenComputers to run.

**Comment by justjosephbird** [comment]
Now it says ship is too big (max 100 per side).
The dimensions are Front:70, Right:72, Up: 9, Back: 100, Left: 72, Down: 70.
Why won't it work now?

**Comment by LemADEC** [comment]
Max ship size is defined in the configuration, feel free to bump it up to 256.
You also need to increase forge chunkloading limit from 25 to 289.

**Comment by justjosephbird** [comment]
How do I increase forge chunkloading limit?

**Comment by justjosephbird** [comment]
Well, I tried again , this time it almost worked, but this time it said, "Not enough space to jump!" But there is nothing above it and i'm trying to go up.

**Comment by justjosephbird** [comment]
Ok, I got it working now, all except it says ship extended over too many chunks. Max is S:25. Aborting.
Is there a way I could make it larger?

**Comment by justjosephbird** [comment]
Now it almost works except it says, "Not enough space for jump!"
There is nothing above it though, and I am trying to go up.

**Comment by justjosephbird** [comment]
All right! It works now. Thanks!
