### ISSUE TITLE
Chunk loading faulty? 

### ISSUE THREAD

**Issue by tdn982** [LemADEC/WarpDrive#156]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/11/16 8:50 PM
Description: Ticking entity

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.WorldUtil.otherModGenerate(IILnet/minecraft/world/World;Lnet/minecraft/world/chunk/IChunkProvider;Lnet/minecraft/world/chunk/IChunkProvider;)V
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
    at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
    at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:138)
    at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:240)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:505)
    at cr0s.warpdrive.EntityJump.moveEntities(EntityJump.java:1164)
    at cr0s.warpdrive.EntityJump.func_70071_h_(EntityJump.java:195)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
    at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
    at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:138)
    at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:240)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:505)
    at cr0s.warpdrive.EntityJump.moveEntities(EntityJump.java:1164)
    at cr0s.warpdrive.EntityJump.func_70071_h_(EntityJump.java:195)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: WarpDrive.EntityJump (cr0s.warpdrive.EntityJump)
    Entity ID: 790
    Entity Name: entity.WarpDrive.EntityJump.name
    Entity's Exact location: 155.50, 143.50, 92.50
    Entity's Block location: World: (155,143,92), Chunk: (at 11,8,12 in 9,5; contains blocks 144,0,80 to 159,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: World
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 307 Drop: 33
    Level seed: -5175143566530854979
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 2;7;1;village
    Level spawn location: World: (153,4,79), Chunk: (at 9,0,15 in 9,4; contains blocks 144,0,64 to 159,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 78554 game time, 9534 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 49236 (now: false), thunder time: 25873 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 85871960 bytes (81 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 33 mods loaded, 33 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items] (Not-Enough-Items-1.7.10.jar) 
    UCHIJAAAA   voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
    UCHIJAAAA   WarpDriveCore{1.7.10-1.3.18.-} [WarpDriveCore] (minecraft.jar) 
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
    UCHIJAAAA   Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) 
    UCHIJAAAA   nevermine{1.1.1} [Nevermine] (AdventOfAscensionV2.0.jar) 
    UCHIJAAAA   ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
    UCHIJAAAA   Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
    UCHIJAAAA   ComputerCraft{1.75} [ComputerCraft] (ComputerCraft-Mod-1.7.10.jar) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   IC2{2.2.791-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
    UCHIJAAAA   VoltzEngine{0.11.17.85} [Voltz Engine] (VoltzEngine-1.7.10-0.11.17b85-dev-universal.jar) 
    UCHIJAAAA   icbm{2.10.0.113} [ICBM] (ICBM-1.7.10-2.10.0b113-dev-universal.jar) 
    UCHIJAAAA   lootbags{1.0} [Loot Bags] (LootBags Mod 1.7.10.jar) 
    UCHIJAAAA   lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
    UCHIJAAAA   me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
    UCHIJAAAA   AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
    UCHIJAAAA   movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) 
    UCHIJAAAA   OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
    UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) 
    UCHIJAAAA   torchLevers{1.4} [Torch Levers] (Torch-Levers-Mod-1.7.10.jar) 
    UCHIJAAAA   WarpDrive{1.7.10-1.3.18.-} [WarpDrive] (WarpDrive-1.7.10-1.3.18.-.jar) 
    UCHIJAAAA   voxelmap{1.7.10} [VoxelMap No Radar] (Zans-MinimapNoRadar-Mod-1.7.10 (1).jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [GCEntityPlayerMP['ShadowCorps'/4, l='World', x=156.00, y=143.00, z=99.00]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by tdn982** [comment]
Don't ask what those mods are doing there.

**Comment by tdn982** [comment]
Without Galacticraft...

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 4/11/16 8:57 PM
Description: Starting integrated server

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:52)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2091)
    at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:696)
    at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
    at net.minecraft.client.gui.GuiSelectWorld.func_146284_a(GuiSelectWorld.java:130)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at info.mineshafter.GameStarter.main(GameStarter.java:24)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 23 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at micdoodle8.mods.miccore.MicdoodleTransformer.startInjection(MicdoodleTransformer.java:1744)
    at micdoodle8.mods.miccore.MicdoodleTransformer.transformCustomAnnotations(MicdoodleTransformer.java:885)
    at micdoodle8.mods.miccore.MicdoodleTransformer.transform(MicdoodleTransformer.java:296)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:52)

-- Starting integrated server --
Details:
    Level ID: World
    Level Name: World
Stacktrace:
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2091)
    at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:696)
    at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
    at net.minecraft.client.gui.GuiSelectWorld.func_146284_a(GuiSelectWorld.java:130)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at info.mineshafter.GameStarter.main(GameStarter.java:24)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 194856280 bytes (185 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 32 mods loaded, 32 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
    UCHIJA  Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.3.74} [Not Enough Items] (Not-Enough-Items-1.7.10.jar) 
    UCHIJA  voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
    UCHIJA  WarpDriveCore{1.7.10-1.3.18.-} [WarpDriveCore] (minecraft.jar) 
    UCHIJA  battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
    UCHIJA  Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) 
    UCHIJA  nevermine{1.1.1} [Nevermine] (AdventOfAscensionV2.0.jar) 
    UCHIJA  ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
    UCHIJA  Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
    UCHIJA  ComputerCraft{1.75} [ComputerCraft] (ComputerCraft-Mod-1.7.10.jar) 
    UCHIJA  customnpcs{1.7.10d} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar) 
    UCHIJA  DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
    UCHIJA  eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJA  VoltzEngine{0.11.17.85} [Voltz Engine] (VoltzEngine-1.7.10-0.11.17b85-dev-universal.jar) 
    UCHIJA  icbm{2.10.0.113} [ICBM] (ICBM-1.7.10-2.10.0b113-dev-universal.jar) 
    UCHIJA  IC2{2.2.791-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UCHIJA  lootbags{1.0} [Loot Bags] (LootBags Mod 1.7.10.jar) 
    UCHIJA  lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
    UCHIJA  malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
    UCHIJA  malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
    UCHIJA  me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
    UCHIJA  AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
    UCHIJA  movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) 
    UCHIJA  OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
    UCHIJA  secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) 
    UCHIJA  torchLevers{1.4} [Torch Levers] (Torch-Levers-Mod-1.7.10.jar) 
    UCHIJA  WarpDrive{1.7.10-1.3.18.-} [WarpDrive] (WarpDrive-1.7.10-1.3.18.-.jar) 
    UCHIJA  voxelmap{1.7.10} [VoxelMap No Radar] (Zans-MinimapNoRadar-Mod-1.7.10 (1).jar) 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4000'
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3345, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by LemADEC** [comment]
Your second crash is because you have Micdoodlecore without Galacticraft. You need to remove both to test it.

Which dimension are you trying to reach?

**Comment by LemADEC** [comment]
Your first crash could be an old mod not updated to your version of Galacticraft or your version of Micdoodlecore being out of sync with your version of Galacticraft.
Either way, this is not a WarpDrive bug.

**Comment by LemADEC** [comment]
No update, not a WarpDrive issue, closing
