### ISSUE TITLE
Autosave should create folders

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#212]
Hi Lemadec,

I've got a weird one with the latest release (.29)... Looks like the schematics for ships do not save right?

```
[13:21:01] [Server thread/INFO]: JumpSequencer/732011827 '1ebe8b2a-b9a6-43d8-b7dc-757f552c454f:Millenium Falcon' @ 'DIM-65' (-999 240 -1500) #4 Saving ship state prior to jump in warpDrive_schematics/auto/Millenium Falcon_2016-09-25_13h21m01s934.schematic
[13:21:01] [Server thread/WARN]: java.io.IOException: No such file or directory
[13:21:01] [Server thread/WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[13:21:01] [Server thread/WARN]:        at java.io.File.createNewFile(File.java:1012)
[13:21:01] [Server thread/WARN]:        at cr0s.warpdrive.event.JumpSequencer.writeNBTToFile(JumpSequencer.java:455)
[13:21:01] [Server thread/WARN]:        at cr0s.warpdrive.event.JumpSequencer.state_borders(JumpSequencer.java:436)
[13:21:01] [Server thread/WARN]:        at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:197)
[13:21:01] [Server thread/WARN]:        at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24)
[13:21:01] [Server thread/WARN]:        at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:79)
[13:21:01] [Server thread/WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_580_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
[13:21:01] [Server thread/WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[13:21:01] [Server thread/WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[13:21:01] [Server thread/WARN]:        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
[13:21:01] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
[13:21:01] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[13:21:01] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)

```

**Comment by LemADEC** [comment]
The mod save backup of ships before each jump but never creates the folder for it. Create the folder manually to fix it, or just ignore the error.

**Comment by StargateMC** [comment]
Where does the folder need to be ? :)

**Comment by LemADEC** [comment]
It's on the first line of your log: warpDrive_schematics/auto/...
You need to create the auto folder in the warpDrive_schematics one. The latest is in your server root, next to mods etc.

**Comment by StargateMC** [comment]
server root - gotcha. Couldn't see that schematics folder either haha
