### ISSUE TITLE
Client crash in unknown dimensions

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#261]
Hi Lemadec,

Testing thoroughly ;)

Looks like theres something wrong with rendering the overlay for a player without oxygen equipment. Doesn't crash all the time...

```
---- Minecraft Crash Report ----
// My bad.

Time: 5/13/17 8:48 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cr0s.warpdrive.render.RenderOverlayAir.renderAir(RenderOverlayAir.java:39)
	at cr0s.warpdrive.render.RenderOverlayAir.onRender(RenderOverlayAir.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_205_RenderOverlayAir_onRender_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderAir(GuiIngameForge.java:309)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:139)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
```

**Comment by LemADEC** [comment]
Fixed in dev
