### ISSUE TITLE
Crash with Defense Tech

### ISSUE THREAD

**Issue by mzldh** [LemADEC/WarpDrive#274]
HI
In my new modpack, my game crashed during start up after installing Defense Tech.
After trying out a few times, I found out that the two mods Warp drive and Defense Tech can't be put together. Which is weird because they worked fine together in my last modpack.

heres the crash log, the defense tech developer isn't responding, so it would be great if you have some time to help, Thankyou!

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 17-7-30 下午11:52
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cr0s/warpdrive/block/TileEntityAbstractChunkLoading
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:117)
Caused by: java.lang.NoClassDefFoundError: cr0s/warpdrive/block/TileEntityAbstractChunkLoading
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:317)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:505)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 15 more
Caused by: java.lang.ClassNotFoundException: cr0s.warpdrive.block.TileEntityAbstractChunkLoading
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: cr0s/warpdrive/block/TileEntityAbstractEnergy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: cr0s.warpdrive.block.TileEntityAbstractEnergy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141647720 bytes (135 MB) / 386928640 bytes (369 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -Xincgc -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128m -Xmx8192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	CodeChickenCore{1.0.3.23} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.3.null} [Not Enough Items] ([NEI][NotEnoughItems].jar) 
	UC	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UC	OpenComputers|Core{1.6.2.12} [OpenComputers (Core)] (minecraft.jar) 
	UC	SmartCore{1.0} [Smart Core] (minecraft.jar) 
	UC	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UC	WarpDriveCore{1.7.10-1.3.29.-} [WarpDriveCore] (minecraft.jar) 
	UC	securitycraft{v1.8.2.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.1.jar) 
	UC	Waila{1.5.4a} [Waila] ([NEI][Waila NEI].jar) 
	UC	antiidconflict{1.1} [Anti Id Conflict] (AntiIdConflict-LATEST-1.7.10.jar) 
	UC	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18-core.jar) 
	UC	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18-builders.jar) 
	UC	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18-energy.jar) 
	UC	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18-factory.jar) 
	UC	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18-silicon.jar) 
	UC	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UC	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	OpenComputers{1.6.2.12} [OpenComputers] (OpenComputers-MC1.7.10-1.6.2.12-universal.jar) 
	UC	CompactMachines{1.7.10-1.21} [Compact Machines] (compactmachines-1.7.10-1.21.jar) 
	UC	DamageIndicatorsMod{3.2.0} [Damage Indicators] (DamageIndicators 伤害与血量显示 v3.2.0.jar) 
	UC	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UC	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46.jar) 
	UC	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UC	flansmod{4.10.0} [Flan's Mod] (Flan's Mod Plus 1.0.4-1.7.10.jar) 
	UC	MapWriter{2.1.1} [MapWriter] (Flan's Mod Plus 1.0.4-1.7.10.jar) 
	UC	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UC	ImmersiveEngineering{0.7.8} [Immersive Engineering] (ImmersiveEngineering-0.7.8.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-fairplay.jar) 
	UC	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UC	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UC	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UC	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UC	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UC	NVLWarpdriveExtensions{1.7.10.1558.1.14} [NVLWarpdriveExtensions] (NVLWarpdriveExtensions-1.7.10.1558.1.14.jar) 
	UC	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UC	OpenPeripheralCore{1.4} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.4.jar) 
	UC	OpenPeripheral{0.6} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.6.jar) 
	UC	OpenPeripheralIntegration{0.6} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.6.jar) 
	UC	openprinter{0.1.0.132} [OpenPrinter] (OpenPrinter-MC1.7.10-0.1.0.132.jar) 
	UC	openradio{0.6.1} [OpenRadio] (OpenRadio-0.6.1.jar) 
	UC	opensecurity{1.0.99} [OpenSecurity] (OpenSecurity-1.7.10-1.0-99.jar) 
	UC	tc{4.3.2_009} [Traincraft] (Traincraft-4.3.2_009.jar) 
	UE	WarpDrive{1.7.10-1.3.29.-} [WarpDrive] (WarpDrive-1.7.10-1.3.29.-.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@5be0d10f) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@559c1e94) returned non-null result: 0

**Comment by LemADEC** [comment]
You need to have CoFH or IC2 for energy to be working.
You want to use version 1.3.30.
