### ISSUE TITLE
Crash On Starting With Thut's Elevators mod

### ISSUE THREAD

**Issue by mzldh** [LemADEC/WarpDrive#293]
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 17-9-17 下午5:39
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thut/tech/common/blocks/lift/TileEntityLiftAccess
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:154)
Caused by: java.lang.NoClassDefFoundError: thut/tech/common/blocks/lift/TileEntityLiftAccess
	at thut.tech.common.handlers.BlockHandler.registerBlocks(BlockHandler.java:30)
	at thut.tech.common.TechCore.preInit(TechCore.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 15 more
Caused by: java.lang.ClassNotFoundException: thut.tech.common.blocks.lift.TileEntityLiftAccess
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/prefab/TileEntityEnvironment
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.prefab.TileEntityEnvironment
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 49 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 778933144 bytes (742 MB) / 1219784704 bytes (1163 MB) up to 10745020416 bytes (10247 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 40 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: lain.mods.inputfix.InputFixTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: code.elix_x.coremods.antiidconflict.core.AntiIdConflictTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cr0s.warpdrive.core.ClassTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: tterrag.core.common.transform.TTCoreTransformer
          - Transformer: tterrag.core.common.transform.TTCoreTransformerClient
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx10260m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 75 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] ([物品管理器]NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	WarpDriveCore{1.7.10-1.3.34.-} [WarpDriveCore] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	securitycraft{v1.8.2.1} [SecurityCraft] ([1.7.10] 安全工艺 v1.8.2.1.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] ([AE]appliedenergistics2-rv2-stable-10.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	ae2stuff{0.5.1.61} [AE2 Stuff] ([AE拓展]ae2stuff-0.5.1.61-mc1.7.10 - 副本.jar) 
	UCH	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCH	BuildCraft|Core{7.1.22} [BuildCraft] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Transport{7.1.22} [BC Transport] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Factory{7.1.22} [BC Factory] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Silicon{7.1.22} [BC Silicon] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Robotics{7.1.22} [BC Robotics] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Energy{7.1.22} [BC Energy] ([BC]buildcraft-7.1.22.jar) 
	UCH	BuildCraft|Builders{7.1.22} [BC Builders] ([BC]buildcraft-7.1.22.jar) 
	UCH	secretroomsmod{4.7.1} [The SecretRoomsMod] ([密室]secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCH	IC2{2.2.827-experimental} [IndustrialCraft 2] ([工业]industrialcraft-2-2.2.827-experimental.jar) 
	UCH	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	Railcraft{9.12.2.0} [Railcraft] (铁路增强Railcraft_1.7.10-9.12.2.0.jar) 
	UCH	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCH	ControlCraft{1.0} [Control Craft] ([无线红石]ControlCraft.jar) 
	UCH	IC2NuclearControl{2.4.3a} [Nuclear Control 2] ([核电控制]IC2NuclearControl-2.4.3a.jar) 
	UCH	ComputerCraft{1.75} [ComputerCraft] ([电脑]ComputerCraft1.75.jar) 
	UCH	Waila{1.5.10} [Waila] ([方块信息显示]Waila-1.5.10_1.7.10.jar) 
	UCH	CompactMachines{1.7.10-1.21} [Compact Machines] ([空间机器]compactmachines-1.7.10-1.21.jar) 
	UCH	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] ([竹]Bamboo-2.6.8.5.jar) 
	UCH	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCH	WarpDrive{1.7.10-1.3.34.-} [WarpDrive] ([飞船]WarpDrive-1.7.10-1.3.34.-.jar) 
	UCH	flansmod{@VERSION@} [Flan's Mod] (flansmod+ forbidden edition.zip) 
	UCE	thutcore{2.0} [ThutCore] (ThutMods-2.1.jar) 
	UCE	ThutConcrete{2.0.0} [Thut's Concrete] (ThutMods-2.1.jar) 
	UCE	ThutTech{2.0.0} [Thut's Tech] (ThutMods-2.1.jar) 
	UCH	ImmersiveEngineering{0.7.8} [Immersive Engineering] (沉浸工程ImmersiveEngineering-0.7.8.jar) 
	UCH	thirstmod{1.8.14} [Thirst Mod] (饮水thirstmod-1.8.14.jar) 
	UCH	NEIAddons{1.12.14.40} [NEI Addons] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	neiintegration{1.1.1} [NEI Integration] ([NEI扩展]NEIIntegration-MC1.7.10-1.1.1.jar) 
	UCH	Ic2Nei{1.0} [IC2 Nei Plugin] ([NEI植物杂交插件]IC2 Nei Plugin Version 1.1.0.jar) 
	UCH	FastCraft{1.21} [FastCraft] ([游戏优化]fastcraft-1.21.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([物品整理]InventoryTweaks-1.59-dev-152.jar) 
	UCH	AppleCore{1.3.9} [AppleCore] (AppleCore-mc1.7.10-1.3.9.jar) 
	UCH	ReiMinimap{1.7.10} [Rei's Minimap] (Reis Minimap.jar) 
	UCH	ttCore{MC1.7.10-0.1.1-78} [ttCore] (ttCore-MC1.7.10-0.1.1-78.jar) 
	UCH	antiidconflict{1.1} [Anti Id Conflict] (优化AntiIdConflict-LATEST-1.7.10.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (合成修改MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	modtweaker2{0.9.6} [Mod Tweaker 2] (合成修改ModTweaker2-0.9.6.jar) 
	UCH	IguanaTweaks{2B} [Iguana Tweaks] (负重IguanaTweaks-1.7.10-2B.jar) 
	UCH	HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (饥饿改革HungerOverhaul-1.7.10-1.0.0.jenkins104.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] ([我的工厂]MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.4-329
	MineFactoryReloaded: -[1.7.10]2.8.2B1-201
	List of loaded APIs: 
		* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.9.jar
		* appliedenergistics2|API (rv2) from [AE]appliedenergistics2-rv2-stable-10.jar
		* BambooAPI|Core (1.0) from [竹]Bamboo-2.6.8.5.jar
		* BuildCraftAPI|blocks (1.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|blueprints (1.5) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|boards (2.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|core (2.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|crops (1.1) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|events (2.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|facades (1.1) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|filler (4.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|fuels (2.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|gates (4.1) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|items (1.1) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|library (2.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|lists (1.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|power (1.3) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|recipes (3.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|robotics (3.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|statements (1.1) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|tablet (1.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|tiles (1.2) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tools (1.0) from [BC]buildcraft-7.1.22.jar
		* BuildCraftAPI|transport (4.1) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* CoFHAPI (1.7.10R1.0.2) from [空间机器]compactmachines-1.7.10-1.21.jar
		* CoFHAPI|block (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from [BC]buildcraft-7.1.22.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|transport (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* ComputerCraft|API (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from [电脑]ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from [电脑]ComputerCraft1.75.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* IC2API (1.0) from [工业]industrialcraft-2-2.2.827-experimental.jar
		* ImmersiveEngineering|API (1.0) from 沉浸工程ImmersiveEngineering-0.7.8.jar
		* NuclearControlAPI (v1.0.5) from [核电控制]IC2NuclearControl-2.4.3a.jar
		* OpenComputersAPI|Component (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Core (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Driver (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Driver|Item (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Event (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|FileSystem (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Internal (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Machine (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Manual (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Network (5.5.3) from ThutMods-2.1.jar
		* OpenComputersAPI|Prefab (5.5.3) from ThutMods-2.1.jar
		* RailcraftAPI|bore (1.0.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|carts (1.6.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|core (1.5.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|crafting (1.0.0) from 沉浸工程ImmersiveEngineering-0.7.8.jar
		* RailcraftAPI|electricity (2.0.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|events (1.0.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|fuel (1.0.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|helpers (1.1.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|items (1.0.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|locomotive (1.1.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|signals (2.3.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|tracks (2.3.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* SecurityCraftAPI (1.2.1) from [1.7.10] 安全工艺 v1.8.2.1.jar
		* Thaumcraft|API (4.2.2.0) from 铁路增强Railcraft_1.7.10-9.12.2.0.jar
		* WailaAPI (1.2) from [方块信息显示]Waila-1.5.10_1.7.10.jar
```

crash on starting when have Thut's Elevators mod instaled https://minecraft.curseforge.com/projects/thuts-elevators?gameCategorySlug=mc-mods&projectID=224375 

That's a bug in Thut's Elevators mods. It shouldn't be distributing the OC API.

**Comment by blazeron10** [comment]
umm... you forgot to get the thut core what i will give you a link to you did make this in 2017 so i hope it still helped https://www.curseforge.com/minecraft/mc-mods/thutcore
