### ISSUE TITLE
TEAirGenerator crash

### ISSUE THREAD

**Issue by Sirse** [LemADEC/WarpDrive#349]
MC 1.7.10

`java.lang.ArrayIndexOutOfBoundsException: -2
	at cr0s.warpdrive.block.breathing.TileEntityAirGeneratorTiered.releaseAir(TileEntityAirGeneratorTiered.java:116)
	at cr0s.warpdrive.block.breathing.TileEntityAirGeneratorTiered.func_145845_h(TileEntityAirGeneratorTiered.java:77)
	at net.minecraft.world.World.func_72939_s(World.java:2069)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:514)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:670)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)`

https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/block/breathing/TileEntityAirGeneratorTiered.java#L25
https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/block/breathing/TileEntityAirGeneratorTiered.java#L116

**Comment by LemADEC** [comment]
Please provide full logs so we can check the context, there's probably another error before that explaining the issue.

**Comment by LemADEC** [comment]
No update, assuming fixed
