### ISSUE TITLE
Server crash when failing to restore a ship

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#363]
Step to fix:
1- in the Warpdrive/config.yml, set enable_jump_logs=true to see the exact error
2- reproduce the issue, check the logs just before the crash, it'll tell you what to fix

Related callstack is
```
java.lang.NullPointerException: Exception in server tick loop
    at cr0s.warpdrive.event.JumpSequencer.disable(JumpSequencer.java:189)
    at cr0s.warpdrive.event.DeploySequencer.disable(DeploySequencer.java:43)
```

This is easily reproduced by restoring a ship larger than forge chunkloading limit.

**Comment by LemADEC** [comment]
Already fixed in public alpha 1.12.2
