### ISSUE TITLE
Bad server configuration causing console spam

### ISSUE THREAD

**Issue by Mailovich** [LemADEC/WarpDrive#396]
![ScreenShot_20190825045745](https://user-images.githubusercontent.com/54488836/63644587-1437d000-c6f5-11e9-82aa-c8b573cf082b.png)

https://www.youtube.com/watch?v=I4SVInqVRwg&t=8s
https://www.youtube.com/watch?v=34L0TysGIWg
[latest.log](https://github.com/LemADEC/WarpDrive/files/3537764/latest.log)
[fml-server-latest.log](https://github.com/LemADEC/WarpDrive/files/3537765/fml-server-latest.log)

[fml-junk-earlystartup.log](https://github.com/LemADEC/WarpDrive/files/3537766/fml-junk-earlystartup.log)
[fml-server-3.log](https://github.com/LemADEC/WarpDrive/files/3537767/fml-server-3.log)

[fml-server-2.log](https://github.com/LemADEC/WarpDrive/files/3537768/fml-server-2.log)

with this Mod the problem at the entrance to hell on the server console is written problem with this mod as well with this mod the problem is the creation of the world like there is,server core kcauldron who knows how to fix it?

**Comment by LemADEC** [comment]
You've at least 4 broken plugins from invalid configuration or libraries.
```
[04:44:37] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\MenuServer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
...
[04:44:51] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling PlaceholderAPI v2.10.3 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/cloud/ExpansionCloudManager
...
[04:44:53] [Server thread/ERROR] [ru.tehkode.permissions.bukkit.PermissionsEx/]: [PermissionsEx] 
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
...
[04:44:51] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling PlaceholderAPI v2.10.3 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/cloud/ExpansionCloudManager
...
[04:44:54] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling FiguresFix v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build()Lguava10/com/google/common/cache/Cache;
```

Paper/Spigot async lighting is incompatible with forge mods, it should be disabled.
```
[04:52:26] [PaperSpigot - Lighting Thread/ERROR] [WarpDrive/]: Server world DIM-1 chunk [-5, 4] is being added to the registry outside main thread!
[04:52:26] [PaperSpigot - Lighting Thread/ERROR] [WarpDrive/]: "PaperSpigot - Lighting Thread"
```

**Comment by Mailovich** [comment]
I wrote that the plugins are not what's tested and without plugins so it was when in hell are still have problems if you put the warpdrive and galaticraft also have the problem

**Comment by Mailovich** [comment]
if you remove the plugins and create again the world is still a problem at the entrance to the hell writes errors in console

**Comment by Mailovich** [comment]
new log:
[fml-server-latest.log](https://github.com/LemADEC/WarpDrive/files/3538320/fml-server-latest.log)
[fml-server-3.log](https://github.com/LemADEC/WarpDrive/files/3538321/fml-server-3.log)
[fml-server-2.log](https://github.com/LemADEC/WarpDrive/files/3538322/fml-server-2.log)
[latest.log](https://github.com/LemADEC/WarpDrive/files/3538323/latest.log)

**Comment by LemADEC** [comment]
Latest is a GalaticCraft crash:
```
[18:54:16] [Server thread/ERROR] [FML/]: Caught exception from GalacticraftCore
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.initialiseDimensionNames(WorldUtil.java:399) ~[WorldUtil.class:?]
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.serverStarting(GalacticraftCore.java:567) ~[GalacticraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:283) [FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:367) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
There's still plenty of plugin and mods erroring in there.

Previous latest is a world generation timeout, no relation with WarpDrive:
```
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:208)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:170)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:315)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.World.func_72964_e(World.java:751)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.World.func_147439_a(World.java:677)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.WorldGenHellLava.func_76484_a(SourceFile:27)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderHell.func_73153_a(ChunkProviderHell.java:526)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:419)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1187)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:303)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		kcauldron.ChunkGenerator.internalGenerate(ChunkGenerator.java:71)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		kcauldron.ChunkGenerator.chunkGeneratorCycle(ChunkGenerator.java:50)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[18:26:45] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.lang.Thread.run(Thread.java:748)
```

**Comment by Mailovich** [comment]
the problem was in the plugin AutoSaveWorld and it is solved now all the rules
