### ISSUE TITLE
Incompatible with Matter Overdrive: Legacy Edition

### ISSUE THREAD

**Issue by peijie7788** [LemADEC/WarpDrive#407]
**Describe the bug**
Game crashes on startup with only JEI, Warpdrive and Matter Overdrive installed. 

**Logs**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WarpDriveCore (WarpDrive-1.12.2-1.5.11.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/23/19 8:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WarpDrive (warpdrive)
Caused by: java.lang.NullPointerException
	at matteroverdrive.blocks.BlockBoundingBox.func_176195_g(BlockBoundingBox.java:109)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at cr0s.warpdrive.config.Dictionary.adjustHardnessAndResistance(Dictionary.java:652)
	at cr0s.warpdrive.config.Dictionary.apply(Dictionary.java:589)
	at cr0s.warpdrive.config.WarpDriveConfig.onFMLPostInitialization(WarpDriveConfig.java:1653)
	at cr0s.warpdrive.WarpDrive.onFMLPostInitialization(WarpDrive.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 178268632 bytes (170 MB) / 1155530752 bytes (1102 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                | Source                                       | Signature                                |
	|:----- |:--------------- |:---------------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft       | 1.12.2                 | minecraft.jar                                | None                                     |
	| LCHIJ | mcp             | 9.42                   | minecraft.jar                                | None                                     |
	| LCHIJ | FML             | 8.0.99.99              | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCHIJ | forge           | 14.23.5.2847           | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCHIJ | WarpDriveCore   | 1.12.2-1.5.11.SNAPSHOT | minecraft.jar                                | None                                     |
	| LCHIJ | jei             | 4.15.0.291             | jei_1.12.2-4.15.0.291.jar                    | None                                     |
	| LCHIE | warpdrive       | 1.12.2-1.5.11.SNAPSHOT | WarpDrive-1.12.2-1.5.11.jar                  | f7be6b40743c6a8205df86c5e57547d578605d8a |
	| LCHI  | matteroverdrive | 0.7.0.0                | MatterOverdrive-1.12.2-0.7.1.0-universal.jar | None                                     |

	Loaded coremods (and transformers): 
WarpDriveCore (WarpDrive-1.12.2-1.5.11.jar)
  cr0s.warpdrive.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.39' Renderer: 'GeForce GTX 980M/PCIe/SSE2'

**Comment by LemADEC** [comment]
That's bug on MatterOverdrive side.

**Comment by LemADEC** [comment]
A workaround is added in the next update
