### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by FomaDima** [LemADEC/WarpDrive#409]
Time: 10/31/19 11:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WarpDrive (warpdrive)
Caused by: java.lang.NullPointerException
	at network.rs485.logisticspipes.proxy.mcmp.subproxy.LPTileMultipartContainer.checkLocalPartsFieldInit(LPTileMultipartContainer.java:115)
	at network.rs485.logisticspipes.proxy.mcmp.subproxy.LPTileMultipartContainer.getParts(LPTileMultipartContainer.java:105)
	at mcmultipart.block.BlockMultipartContainer.lambda$addF$80([LP|ASM] BlockMultipartContainer.java:628)
	at mcmultipart.block.BlockMultipartContainer$$Lambda$8027/1516987785.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at mcmultipart.block.BlockMultipartContainer.addF([LP|ASM] BlockMultipartContainer.java:628)
	at mcmultipart.block.BlockMultipartContainer.getExplosionResistance([LP|ASM] BlockMultipartContainer.java:339)
	at logisticspipes.pipes.basic.ltgpmodcompat.LPMicroblockBlock.getExplosionResistance(LPMicroblockBlock.java:238)
	at cr0s.warpdrive.config.Dictionary.adjustHardnessAndResistance(Dictionary.java:654)
	at cr0s.warpdrive.config.Dictionary.apply(Dictionary.java:589)
	at cr0s.warpdrive.config.WarpDriveConfig.onFMLPostInitialization(WarpDriveConfig.java:1653)
	at cr0s.warpdrive.WarpDrive.onFMLPostInitialization(WarpDrive.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LemADEC** [comment]
Crash is incomplete, version are missing.
There's an issue template, it's not optional, use it!
