### ISSUE TITLE
Crash when first generating world with warpdrive and spongeforge

### ISSUE THREAD

**Issue by IronworksProductions** [LemADEC/WarpDrive#430]
**Describe the bug**
Server crash when generating world for first time with warpdrive when spongeforge and astral sorcery is installed.
**To Reproduce**
1.  reset main spawn world on spongeforge 
2.  start server
3.  wait for it to start generating terrain
4.  https://gist.github.com/nacjm/5eaff887145cbe8a89af0d5d65b6ae97

**Expected behavior**
Server should not crash from warpdrive.
**Screenshots**

**Logs**
Link to pastebin/gist or equivalent logs
https://gist.github.com/nacjm/5eaff887145cbe8a89af0d5d65b6ae97
**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.12
-   Forge version: latest 1.12.2
-   Modpack name/version:  ROC Framework 17.3(custom modpack)
-   Other notable mods & version: https://www.technicpack.net/modpack/pktl.1439167/mods

**Additional context**
Crash only seems to occur when first generating the world with warpdrive.

**Comment by LemADEC** [comment]
We need the server log that comes with the crash report. There should be an error or info just before the crash telling what happened.

**Comment by IronworksProductions** [comment]
Here you go:https://gist.github.com/nacjm/d1ed906a549047ae38ddf83a4dcdb23f

**Comment by LemADEC** [comment]
World generation is detected outside the main thread, causing multiple errors, like:
```
[20:13:54] [Server thread/ERROR] [warpdrive]: Server world DIM0 chunk [-17, 4] is being added to the registry outside main thread!
...
[20:13:57] [Sponge - Async Light Thread/ERROR] [Sponge]: Attempted to call MapStorage#setData from off the main thread!
...

"Ore Query Limiter"
	java.lang.Thread.State: RUNNABLE
		at sun.management.ThreadImpl.getThreadInfo1(Native Method)
		at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:178)
		at cr0s.warpdrive.Commons.dumpAllThreads(Commons.java:908)
		at cr0s.warpdrive.event.ChunkHandler.getChunkData(ChunkHandler.java:333)
		at cr0s.warpdrive.event.ChunkHandler.onLoadChunkData(ChunkHandler.java:104)
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2805_ChunkHandler_onLoadChunkData_Load.invoke(.dynamic)
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
		at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753)
		at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
		at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:103)
		at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
		at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
		at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
		at net.minecraft.world.gen.ChunkProviderServer.redirect$impl$ProvideChunkForced$znd000(ChunkProviderServer.java:1658)
		at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
		at net.minecraft.server.MinecraftServer.bridge$prepareSpawnArea(MinecraftServer.java:4447)
		at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:882)
		at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:820)
		at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4397)
		at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
		at java.lang.Thread.run(Thread.java:748)
...
[20:13:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 9%
[20:13:58] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:stone[variant=stone] @ earth (-249 13 243)
[20:13:59] [ForkJoinPool.commonPool-worker-3/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [MSDataSync] Optimization complete! Uploaded 0 snapshots and removed 0 snapshots from 0 users!
[20:13:59] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:obsidian @ earth (-247 10 364)
[20:13:59] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:obsidian @ earth (-247 10 364)
[20:13:59] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:obsidian @ earth (-248 10 363)
[20:13:59] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:obsidian @ earth (-248 10 363)
[20:13:59] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 11%
[20:13:59] [Server thread/ERROR] [warpdrive]: Non-threadsafe call to StarMapRegistry:onBlockUpdating outside main thread, for minecraft:torch[facing=east] @ earth (-242 30 385)
```

So you have at least 2 issues causing bad multi-threading here:
- Ore query limiter (which mod/plugin is doing that)
- Async lighting (Sponge and a few other mods are doing that)

You need to fix all those or you world will corrupt and crash in weird ways due to bad multi-threading.

**Comment by LemADEC** [comment]
Technically speaking, there's still a weakness in WarpDrive that'll be fixed in next update.

**Comment by iocmet** [comment]
Why warpdrive not likes adding chunks from other threads? I ran into this issue when using pregenerator plugin (https://dev.bukkit.org/projects/pregenerator)

**Comment by LemADEC** [comment]
> Why warpdrive not likes adding chunks from other threads? I ran into this issue when using pregenerator plugin (https://dev.bukkit.org/projects/pregenerator)

please don't necropost on obsolete issues.
Also, the base vanilla game doesn't support loading chunks from other threads. WarpDrive protect your save when it affects the mods' blocks.
