### ISSUE TITLE
game crashing on start

### ISSUE THREAD

**Issue by Luckyradkid1** [LemADEC/WarpDrive#455]
um, game crashed when i try to load up warpdrive, i have CC tweaked and TechGuns, also same thing happens without techguns. im playing using MultiMC

steps to reproduce.... um mods loaded, and i press launch, then it crashed

i expect that wehn i press launch i get to play

this is the log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WarpDriveCore (WarpDrive-1.12.2-1.5.12.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/26/20 6:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WarpDrive (warpdrive)
Caused by: java.lang.RuntimeException: Invalid celestial objects definition: update your configuration to fix this validation error, search your logs for 'CelestialObjects validation error' to get more details.
	at cr0s.warpdrive.data.CelestialObjectManager.rebuildAndValidate(CelestialObjectManager.java:404)
	at cr0s.warpdrive.data.CelestialObjectManager.load(CelestialObjectManager.java:149)
	at cr0s.warpdrive.config.WarpDriveConfig.onFMLpreInitialization(WarpDriveConfig.java:729)
	at cr0s.warpdrive.WarpDrive.onFMLPreInitialization(WarpDrive.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.3.0-24-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 3003334016 bytes (2864 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version                | Source                                  | Signature                                |
	|:----- |:------------- |:---------------------- |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft     | 1.12.2                 | minecraft.jar                           | None                                     |
	| LCH   | mcp           | 9.42                   | minecraft.jar                           | None                                     |
	| LCH   | FML           | 8.0.99.99              | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge         | 14.23.5.2854           | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | WarpDriveCore | 1.12.2-1.5.12.SNAPSHOT | minecraft.jar                           | None                                     |
	| LCH   | cctweaked     | 1.86.0                 | cc-tweaked-1.12.2-1.86.0.jar            | None                                     |
	| LCH   | computercraft | 1.86.0                 | cc-tweaked-1.12.2-1.86.0.jar            | None                                     |
	| LCE   | warpdrive     | 1.12.2-1.5.12.SNAPSHOT | WarpDrive-1.12.2-1.5.12.jar             | f7be6b40743c6a8205df86c5e57547d578605d8a |

	Loaded coremods (and transformers): 
WarpDriveCore (WarpDrive-1.12.2-1.5.12.jar)
  cr0s.warpdrive.core.ClassTransformer
	GL info: ' Vendor: 'X.Org' Version: '3.1 Mesa 19.0.8' Renderer: 'AMD TURKS (DRM 2.50.0 / 5.3.0-24-generic, LLVM 8.0.0)'

-   WarpDrive version: warpdrive 1.5.13
-   Forge version: 14.23.5.2854
-   Modpack name/version: 1.12.2
-   Other notable mods & version: techguns and cctweaked

**Comment by LemADEC** [comment]
You are using version 1.5.12. Update to latest.
Also, you've changed your celestial objects configuration and it's invalid, follow the crash report instruction or reset your configuration: Invalid celestial objects definition: update your configuration to fix this validation error, search your logs for 'CelestialObjects validation error' to get more details.

**Comment by LemADEC** [comment]
Also, that bug report is from 2 days ago, so it's probably not the right log.
Last but not least, you should use gist or pastebin to post your logs.

**Comment by LemADEC** [comment]
No update for 4 weeks, assuming fixed
