### ISSUE TITLE
Broken ICBM-Classic Dependency? 

### ISSUE THREAD

**Issue by x0reaxeax** [LemADEC/WarpDrive#456]
This feels a little bit sketchy, since I couldn't find anyone else experiencing this problem, but WarpDrive is asking for `ICBM-Classic >= 4.0.0` to be present, although, the latest version of ICBM-Classic is `3.3.0` (https://www.curseforge.com/minecraft/mc-mods/icbm-classic).  
Am I missing something here?

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-06-03 16:13:40 CEST
Description: Exception in server tick loop

Missing Mods:
    unknown : need [1.12.2-4.0.0,): have 1.12.2-3.3.0.63

net.minecraftforge.fml.common.MissingModsException: Mod warpdrive (WarpDrive) requires [icbmclassic@[1.12.2-4.0.0,)]
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by LemADEC** [comment]
ICBM 4.x is in alpha for several months and fix many issues from the current beta, so everyone switched to it, see it here: https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2918052

**Comment by x0reaxeax** [comment]
Oh shoot, thank you very much!!
