### ISSUE TITLE
Client crash with SimplyJetpacks and OfflineAvatars

### ISSUE THREAD

**Issue by Famous5000** [LemADEC/WarpDrive#481]
**Describe the bug**
Title.

**To Reproduce**
1.  Tell ship core to engage Jump
2.  Enter a monitor linked to a valid camera before engaging jump
3.  Wait until jump completes
4.  Notice that you cannot exit the camera [in multiplayer at least] and are stuck inside the camera.
5.  Upon leaving, you cannot rejoin the server, doing so ends in a very non-clear error `java.lang.ClassCastException`
6.  Upon trying to restart the server, the server fails to start, I can't get the logs on that yet but will give the logs as soon as possible.

**Expected behavior**
The camera would boot you out upon noticing that it wasn't where it was previously

**Screenshots**

**Logs**
Error report generated via VanillaFix for Step 5: https://pastebin.com/9UxV8Qte
Logs obtained around Step 5's error report: https://pastebin.com/NN9TUGzP
Server logs: *linked in comments*

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.19.SNAPSHOT 
-   Forge version: 14.23.5.2854  
-   Modpack name/version: Iris Heart III 1.1.2
-   Other notable mods & version: 

**Additional context**
The error report for Step 5 was from me after teleporting to affected user.

**Comment by LemADEC** [comment]
The crash seems located in the TheOneProbe, probably from trying to use a client side only entity or something.
Please send full logs and world save, possibly PM me on Discord

**Comment by LemADEC** [comment]
We'll also need the kind of jump happening at that time.

**Comment by Famous5000** [comment]
Noted, I'll try to send the full details over Discord if I can even find it.

Also, this was a long-ranged jump in Hyperspace.

**Comment by LemADEC** [comment]
ok, I can't reproduce in dev, so we'll need:
1- original player client crash report
2- server logs during the original player client crash, preferably the debug logs version
3- your client logs when you went there and crashed
4- server logs from the following boot failure

**Comment by Famous5000** [comment]
I can get those logs soon, one second.
Server logs I cannot obtain yet, server owner has yet to come back online.
I sent the client logs that were relevant; this was running for quite a while.
This log I cannot obtain yet, again, server owner has yet to come back online.

**Comment by Famous5000** [comment]
[latest (2).log](https://github.com/LemADEC/WarpDrive/files/5862991/latest.2.log)
This is from my friend who had the jump. This is the full log that they had, I haven't combed through it yet though so.

Server logs I still can't obtain because the server owner's still offline, same with the world. We did have backups so I will tell him to restore from backup after it's done.

**Comment by VanillaChan6571** [comment]
Hi, As requested (as the server owner)
Server Log is here and now I have to force kill the server (which I never really had to do) since it's still on the stopping server for whatever reason. And for security reasons, I have replaced players IPs with NOPE.

[latest.log](https://github.com/LemADEC/WarpDrive/files/5863227/latest.log)

I also have uploaded the world to a drive. https://1drv.ms/u/s!AknBVjcV1dm-in3_6mMW8xhgejWg?e=Ebj6A6

**Comment by LemADEC** [comment]
latest (2).log is a client log
The original crash comes from ChatTweaks, consider removing it for now. It could be from the server sending messages too soon or some other mods interactions.
```
Time: 2021-01-24 10:31:19 CET
Description: Unexpected error

java.lang.NullPointerException
    at net.blay09.mods.chattweaks.gui.chat.GuiNewChatExt$WrappedChatLine.access$000(GuiNewChatExt.java:31)
    at net.blay09.mods.chattweaks.gui.chat.GuiNewChatExt.drawChat(GuiNewChatExt.java:215)
    at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:827)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:199)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
IndustrialForegoing is corrupting the world, as seen here:
```
[15:36:07] [Netty Client IO #2/ERROR]: Non-threadsafe call to GlobalRegionManager:onBlockUpdating outside main thread, for industrialforegoing:potion_enervator[facing=east] @ solarSystem (-110270 93 109815)
```
The next weird/empty crashes are probably from VanillaFix forcing the game to stay loaded after the initial crash. That feature is very experimental and should be disabled.


latest.log is the server side log.
There's FTB Backup doing world corruption, as seen here:
```
[09:29:57] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Server Backup started!
[09:29:57] [File IO Thread/WARN] []: java.lang.IllegalStateException: Asynchronous Save Players! Blocking thread until it returns 
[09:29:57] [File IO Thread/WARN] []: 	at com.destroystokyo.paper.MCUtil.ensureMain(MCUtil.java:58)
[09:29:57] [File IO Thread/WARN] []: 	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:1526)
[09:29:57] [File IO Thread/WARN] []: 	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:1521)
[09:29:57] [File IO Thread/WARN] []: 	at com.feed_the_beast.mods.ftbbackups.Backups.doBackup(Backups.java:206)
[09:29:57] [File IO Thread/WARN] []: 	at com.feed_the_beast.mods.ftbbackups.Backups.lambda$run$1(Backups.java:184)
[09:29:57] [File IO Thread/WARN] []: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37)
[09:29:57] [File IO Thread/WARN] []: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
[09:29:57] [File IO Thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
[09:29:57] [File IO Thread/INFO] [FTB Backups]: Deleting old backup: 2021-01-23-13-29-56.zip
[09:29:57] [File IO Thread/INFO] [FTB Backups]: Backing up 1486 files...
[09:29:57] [File IO Thread/INFO] [FTB Backups]: Compressing 1486 files...
```
There's a chat mod doing bad multithreading, preventing WarpDrive VirtualAssistant to work properly, other mods may silently corrupt the world, as seen here:
```
[12:04:07] [Async Chat Thread - #73/ERROR] [warpdrive]: Non-threadsafe call to GlobalRegionManager:onChatReceived outside main thread, for EntityPlayerMP['Cpt_Waterbubble'/98531, uuid='9140b200-433d-4842-8d9e-7492b1204671', l='DIM-101', x=-109372.82, y=106.17, z=110941.28, cx=-6836, cd=6933, tl=7547145, v=true, d=false](Cpt_Waterbubble at -109372.82000629643,106.17402004766467,110941.2847062545) neat
```
As for the reported issue:
```
[15:53:35] [Server thread/INFO] [warpdrive]: TileEntityShipCore 'Excalibur' @ Hyperspace (-110060 128 110672) Connected messageToAllPlayersInArea: Ship core is warming up... 20 s to go...
...
[15:53:55] [Server thread/INFO] [warpdrive]: TileEntityShipCore 'Excalibur' @ Hyperspace (-110060 128 110672) Connected Performing manual jump of 14859 blocks inside (-110077 112 110608) to (-110043 131 110689) with an actual mass of 7578 blocks, HYPERSPACE_MOVING, movement VectorI [876 -30 -142], rotationSteps 0
...
[15:53:56] [Server thread/INFO] [warpdrive]: JumpSequencer/260494166 '2d2f38bb-d281-49e0-9ef3-f70256a66d48:Excalibur' @ Hyperspace (-110060 128 110672) #18 Entity moving: (-110058.45 127.00 110678.50) -> (-110200.45 97.00 109802.50) entity EntityPlayerMP['Cpt_Waterbubble'/98531, uuid='9140b200-433d-4842-8d9e-7492b1204671', l='DIM-100', x=-110058.45, y=127.00, z=110678.50, cx=-6879, cd=6917, tl=7820853, v=true, d=false](Cpt_Waterbubble at -110058.44628336768,127.0,110678.49849142169)
...
[15:54:15] [Async Chat Thread - #96/ERROR] [warpdrive]: Non-threadsafe call to GlobalRegionManager:onChatReceived outside main thread, for EntityPlayerMP['Cpt_Waterbubble'/98531, uuid='9140b200-433d-4842-8d9e-7492b1204671', l='DIM-100', x=-110200.45, y=97.00, z=109802.50, cx=-6888, cd=6862, tl=7821246, v=true, d=false](Cpt_Waterbubble at -110200.44628336768,97.0,109802.49849142169) *help I'm stuck in a camera*
...
[15:54:27] [Server thread/DEBUG] [warpdrive]: Spawning offline avatar for EntityPlayerMP['Cpt_Waterbubble'/98531, uuid='9140b200-433d-4842-8d9e-7492b1204671', l='DIM-100', x=-110200.45, y=97.00, z=109802.50, cx=-6888, cd=6862, tl=7821468, v=true, d=false](Cpt_Waterbubble at -110200.44628336768,97.0,109802.49849142169)
```
The client crashed after the jump, and the server has the right coordinates.

Try to reproduce without Vanilla Fix and ChatTweak so we get a proper crash report.
Consider removing Wawla since TheOneProbe is already there and performs generally better.
You could try disabling both temporarily, since they are prone to cause crash when looking at entities or blocks while the world is loading.

**Comment by LemADEC** [comment]
Something is messing around with the WorldInfo object of dimensions, causing invalid folder saves, this will corrupt your world eventually depending on how dimensions are loaded.

Regarding your world file, the crash is reproduced in single player. It is due to SimplyJetpacks, as reported here: https://github.com/Tomson124/SimplyJetpacks2/issues/33
It's a client side crash, so you can fix it by either:
1- removing the Offline avatars while staying away from the area.
2- wait for the mod author to post a fix when they are available.
3- remove the jetpacks from the Offline avatars, like I did in your save here: [r.-216.214.mca.zip](https://github.com/LemADEC/WarpDrive/files/5863577/r.-216.214.mca.zip)

**Comment by LemADEC** [comment]
Also, you might want to disable offline avatar creation while you wait for SimplyJetpacks to be updated. Remember to re-enable it later on so players can share a common ship :).

**Comment by LemADEC** [comment]
As for the player being unable to exit the camera, it should be done automatically by the server. I'm not able to reproduce it, so I suggest you open another issue once you're able to reproduce it.

**Comment by Famous5000** [comment]
Alright, I will see if I can find the SimplyJetpacks git and ask them to patch it, linking to this thread as well. They might throw it back your way saying it's "not their problem" considering it's an issue with the offline avatars, but I am willing to take a gander at suggesting it. Also, no, the client didn't crash, he left because he couldn't exit the camera.

*edit* just noticed that it was already reported, sorry I was doing a quick glance read through everything that's been said. That said, he couldn't exit the camera no matter what he tried. Thank you for being so willing to help, by the way!

**Comment by VanillaChan6571** [comment]
> 
> 
> Also, you might want to disable offline avatar creation while you wait for SimplyJetpacks to be updated. Remember to re-enable it later on so players can share a common ship :).

Will this still move players while offline?

Also, FTB still makes the backup and works 100% fine it probably complains because its using paper+forge which is unsupported with forge in the first place.

Chat Tweaks does have issues but never really has crashed anyone except on login but Vanilla Fix just sends them back to the main menu.

So for now we can disable offline avatars.

We rolled back the server using FTB Backups so it's fine at the moment.

**Comment by LemADEC** [comment]
> > Also, you might want to disable offline avatar creation while you wait for SimplyJetpacks to be updated. Remember to re-enable it later on so players can share a common ship :).
> 
> Will this still move players while offline?

No, that feature is gone if you disable offline avatars. New avatars aren't created and existing ones won't be removed unless you kill them.

> Also, FTB still makes the backup and works 100% fine it probably complains because its using paper+forge which is unsupported with forge in the first place.

The World object shouldn't be accessed outside the main thread. Many mods are mishandling this. The fact that you didn't have an issue yet, doesn't mean it's 100% fine.  
The real question is whether the bug is there with just FTB Backup or it's introduced by one of the many other mods in the pack.  
You could also switch to SpongeForge which actively fixes this kind of issues by rescheduling offenders to the proper thread.

**Comment by VanillaChan6571** [comment]
> You could also switch to SpongeForge which actively fixes this kind of issues by rescheduling offenders to the proper thread.

SpongeForge is absolute garbage having any plugin makers actually switching or supporting that platform. It always has many issues, devs barely keep up on updates or fix bugs. Bungee cord seems to always fail on some updates and not fixed after months. I switched back to thermos (this was 2017 at the time and I still don't hear anything "big" at sponge) At least people who know sponge is a dumpster fire the people who actually came to realize that and started working on thermos/kettle servers are great dev/modders of Minecraft.

With all the risks knowing that some mods don't handle well on Minecraft plugin servers like thermos (I am using Magma Server that adds the latest support for paper + forge) that the mod creators never meant to have it on there in the first place. It could be just a handler issue but I don't see the effects that it may display that you may see as a modder/dev.

As of now seems like turning off avatars will be the work until Simply Jetpacks fixes whatever issue my users have experienced.

Also sorry for the big long response. Whenever I hear SpongeForge it just feels like a bedrock server. Limited choices. Unless I am very wrong and there is a lot more plugins then maybe.

**Comment by LemADEC** [comment]
About 50% of plugins have to be custom made or patched for functional bugs, Bukkit or Sponge, same story.
So, as a server owner, I value my existing working suite of plugins more than some fancy 'new' or 'reborn' platform.
If we have to switch, it better be a very good reason to spend time fixing all those new plugins replacements and then patch all the mods that don't work on that new platform.

As for Bungee, it's intended for Vanilla. It was tolerant with Forge until some server owners went extremely disrespectful, forcing the author to explicitly remove forge support.
If you want a modded proxy, there's a few forks out there that are intended for modded, work just fine from 1.7.10 up, and actually respect the original author.

**Comment by LemADEC** [comment]
A workaround was added in 1.5.20. No update for 2 months on the other subjects, assuming fixed.
