### ISSUE TITLE
WarpDrive running into issues while accessing chunk data.

### ISSUE THREAD

**Issue by OutcastOrange** [LemADEC/WarpDrive#491]
An error repeatedly appears within latest.log. 
Here is an example:

```
[09:58:10] [Server thread/INFO]: java.lang.RuntimeException
[09:58:10] [Server thread/INFO]: 	at cr0s.warpdrive.data.ChunkData.load(ChunkData.java:71)
[09:58:10] [Server thread/INFO]: 	at cr0s.warpdrive.event.ChunkHandler.onLoadChunkData(ChunkHandler.java:110)
[09:58:10] [Server thread/INFO]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1996_ChunkHandler_onLoadChunkData_Load.invoke(.dynamic)
[09:58:10] [Server thread/INFO]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[09:58:10] [Server thread/INFO]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[09:58:10] [Server thread/INFO]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:103)
[09:58:10] [Server thread/INFO]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.World.func_72964_e(World.java:310)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.World.func_175726_f(World.java:305)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.World.func_180495_p(World.java:911)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:233)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:135)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[09:58:10] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[09:58:10] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```

An example log can be found here: https://gist.github.com/OutcastOrange/3867823ea97825759792171df1f28934

To Reproduce:
This might be difficult to reproduce, since I'm playing a custom modpack.
I added the WarpDrive mod to a pre-existing world. These errors happen continually while my world is loaded.
I haven't used any WarpDrive content so far. This is happening while standing in the overworld.
It doesn't seem to interfere with gameplay, but seeing exceptions in the log during play is mildly concerning.

Some mods that might be relevant:
- TerraFirmaCraft-MC1.12.2-1.7.18.176.jar
- gregtech-1.12.2-1.14.0.689.jar (GTCE)
- Xaeros_Minimap_21.5.0_Forge_1.12.jar
- XaerosWorldMap_1.13.1_Forge_1.12.jar

Sorry for this mostly vague information.
I was hoping the creators might have some insight into what is causing this.
Any information you share could lead me to a solution. Thank you.

-   WarpDrive version: WarpDrive-1.12.2-1.5.22.jar
-   Forge version: 8.0.99.99

**Comment by LemADEC** [comment]
This is a log informing you why the chunk was loaded. It's used to investigate lag coming from fast chunk reloading. You can disable it in the mod configuration by setting `enable_chunk_reloading_logs` to false.

**Comment by OutcastOrange** [comment]
"java.lang.RuntimeException
	at cr0s.warpdrive.data.ChunkData.load(ChunkData.java:71)"

> The Runtime Exception is the parent class in all exceptions of the Java programming language that are expected to crash or break down the program or application when they occur

A runtime exception is being used for logging information?
I think you should reread my issue.

Also, why is this changed to an 'improvement' tag? I don't see how this is some kind of an improvement.

**Comment by LemADEC** [comment]
Under normal conditions, a RuntimeException is only the consequence of another exception. The logs shows no such other exception, that should tell you already it's not an actual error, it's just a way to show the call stack.
