### ISSUE TITLE
Crash on startup CreativeTabAbstractBase

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#506]
**Describe the bug**
On server/client startup I encountered a weird crash. WarpDrive cannot find `ItemStack.EMPTY` at runtime when constructing static fields.

Hot fix is to replace line at CreativeTabAbstractBase.java:12 to:
```
private ItemStack itemStack = new ItemStack((Item)null);
```

**To Reproduce**
Start the server or client.

**Expected behavior**
Clean startup.

**Logs**
Short version:
```
Oct 07 17:52:52 main minecraft-server[15572]: [17:52:52] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
Oct 07 17:52:52 main minecraft-server[15572]: java.lang.NoSuchFieldError: EMPTY
Oct 07 17:52:52 main minecraft-server[15572]:         at cr0s.warpdrive.client.CreativeTabAbstractBase.<init>(CreativeTabAbstractBase.java:12) ~[CreativeTabAbstractBase.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at cr0s.warpdrive.client.CreativeTabMain.<init>(CreativeTabMain.java:15) ~[CreativeTabMain.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at cr0s.warpdrive.WarpDrive.<clinit>(WarpDrive.java:363) ~[WarpDrive.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at java.lang.Class.forName0(Native Method) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) ~[LoadController.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) ~[Loader.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
Oct 07 17:52:52 main minecraft-server[15572]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

Full log at https://gist.github.com/NCrashed/16074ed461e47a2e04f7fbedc05c004a

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.23
-   Forge version: 14.23.5.2847
-   Sponge 1.12.2-2838-7.2.3-RC4050
- `appliedenergistics2-rv6-stable-7`
- `cc-tweaked-1.12.2-1.89.1`
- `CodeChickenLib-1.12.2-3.2.3.358-universal`
- `forestry_1.12.2-5.8.2.422`
- `ForgeMultipart-1.12.2-2.6.2.83-universal`
- `IC2Classic+1.12-1.5.5`
- `ICBM-classic-1.12.2-4.0.1b75`
- `ironchest-1.12.2-7.0.72.847`
- `jei_1.12.2-4.15.0.293`
- `journeymap-1.12.2-5.7.1`
- `MrTJPCore-1.12.2-2.1.4.43-universal`
- `OreLib-1.12.2-3.5.2.2`
- `ProjectRed-1.12.2-4.9.4.120` (full pack)
- `RenderPlayerAPI-1.12.2-1.0`
- `WanionLib-1.12.2-2.4`

**Additional context**
The crash occurs on the client and on the server.

**Comment by LemADEC** [comment]
`ItemStack.NULL` comes from Forge if not Vanilla. This is probably a transformer issue triggered by another mod.
authlib, Veinminer, ChatTweaks, etc. appears in those logs. Please provide a client side log with minimal mods.

**Comment by LemADEC** [comment]
At least Forge, IC2Classic, JEI, OreLib, CC:Tweaked, WanionLib are outdated in your setup. Try to reproduce with latest versions.

**Comment by LemADEC** [comment]
Can't reproduce

**Comment by LemADEC** [comment]
Not reproduces, no update for 3 months, assuming fixed
