### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by zyxkad** [LemADEC/WarpDrive#518]
## Logs
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WarpDriveCore (WarpDrive-1.12.2-1.5.26.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/14/22 7:46 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AsmodeusCore (asmodeuscore)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.world.biome.Biome$BiomeProperties.field_185412_a from class asmodeuscore.core.utils.worldengine.WE_Biome
	at asmodeuscore.core.utils.worldengine.WE_Biome.<init>(WE_Biome.java:62)
	at asmodeuscore.core.utils.Utils.<clinit>(Utils.java:30)
	at asmodeuscore.core.registers.potions.ACPotions.initPotions(ACPotions.java:24)
	at asmodeuscore.core.registers.potions.ACPotions.initialize(ACPotions.java:18)
	at asmodeuscore.AsmodeusCore.preInit(AsmodeusCore.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 448419640 bytes (427 MB) / 1073741824 bytes (1024 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                | Source                                        | Signature                                |
	|:----- |:--------------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2                 | minecraft.jar                                 | None                                     |
	| LCH   | mcp                   | 9.42                   | minecraft.jar                                 | None                                     |
	| LCH   | FML                   | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | WarpDriveCore         | 1.12.2-1.5.26.SNAPSHOT | minecraft.jar                                 | None                                     |
	| LCH   | ic2                   | 2.8.221-ex112          | industrialcraft-2-2.8.221-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | advanced_solar_panels | 4.3.0                  | Advanced+Solar+Panels-4.3.0.jar               | None                                     |
	| LCE   | asmodeuscore          | 0.0.30                 | AsmodeusCore-1.12.2-0.0.30.jar                | None                                     |
	| LC    | buildcraftlib         | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftcore        | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftbuilders    | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcrafttransport   | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftsilicon     | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftcompat      | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftenergy      | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftfactory     | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | buildcraftrobotics    | 7.99.24.8              | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LC    | codechickenlib        | 3.2.3.358              | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | gravisuite            | 3.1.1                  | Gravitation Suite-3.1.1.jar                   | None                                     |
	| LC    | jei                   | 4.16.1.301             | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | mantle                | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LC    | mjrlegendslib         | 1.12.2-1.2.1           | MJRLegendsLib-1.12.2-1.2.1.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | nei                   | 2.4.3                  | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | tconstruct            | 1.12.2-2.13.0.183      | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LC    | plustic               | 8.0.0.1                | plustic-8.0.0.1.jar                           | None                                     |
	| LC    | reactor_stuff         | 1.10.2                 | ReactorStuff-[1.12.2]-1.10.2.jar              | None                                     |
	| LC    | warpdrive             | 1.12.2-1.5.26.SNAPSHOT | WarpDrive-1.12.2-1.5.26.jar                   | f7be6b40743c6a8205df86c5e57547d578605d8a |

	Loaded coremods (and transformers): 
WarpDriveCore (WarpDrive-1.12.2-1.5.26.jar)
  cr0s.warpdrive.core.ClassTransformer
	GL info: ' Vendor: 'Apple' Version: '2.1 Metal - 76.3' Renderer: 'Apple M1 Pro'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
```

**Comment by zyxkad** [comment]
I found the problem
I need add this patch <https://github.com/Su5eD/AdvSolarPatch>
