### ISSUE TITLE
game crashes on startup 

### ISSUE THREAD

**Issue by gunboy001** [LemADEC/WarpDrive#53]
Hi! I've tryed to use  warp drive on my modpack but it crashes on startup, here's some informations:
warp drive ver. 1.3.2
mod list:
computercraft 1.7.4
MFR 2.8.1B1127
power converters jenkins fork build 75
railcraft 9.7.0.0
extra utilities 1.2.10
techReborn 0.3.1.740
Immersive engineering 0.5.2
buildcraft 7.0.20
industrialcraft 2-2.2.759-experimental
openMods lib 0.8
openBlocks 1.4.4
immersive integration 0.4.2
all project red files versions 4.7.0pre8.92
cofhCore 3.0.4B1-309
matter overdrive 0.4.0 RC2
thermal foundation 1.2.0-102
thermal expansion 4.0.3B1-218
thermal dynamics 1.1.0-161
highlands 2.2.3
enderIO 2.2.8.381
mapwriter 2.1.4
fastcraft 1.21
compactsolars 4.4.39.315
carpenter's blocks 3.37 DEV
chisel2 2.4.1.40
extra cells 2.2.73b129
applied energistics 2 rv2 stable 10
neiaddons 1.12.10.33
inventory tweaks 1.59 dev 152
NEI 1.0.5.111
ender storage 1.4.7.36
code chicken core 1.0.7.46
wrcbe 1.4.1.9
chicken chunks 1.3.4.19
waila 1.5.10
ironchest 6.0.60.741

Here's the crashlog:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/08/15 19.49
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate id: transporter
    at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:43)
    at cpw.mods.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:281)
    at cr0s.warpdrive.WarpDrive.load(WarpDrive.java:338)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:43)
    at cpw.mods.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:281)
    at cr0s.warpdrive.WarpDrive.load(WarpDrive.java:338)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 184830304 bytes (176 MB) / 921341952 bytes (878 MB) up to 5315035136 bytes (5068 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 91 mods loaded, 90 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHI    Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHI    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHI    OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHI    CoFHCore{1.7.10R3.0.4B1} [CoFH Core](CoFHCore-[1.7.10]3.0.4B1-309.jar) 
    UCHI    BuildCraft|Core{7.0.20} [BuildCraft](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Silicon{7.0.20} [BC Silicon](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Transport{7.0.20} [BC Transport](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Builders{7.0.20} [BC Builders](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Robotics{7.0.20} [BC Robotics](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Energy{7.0.20} [BC Energy](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Factory{7.0.20} [BC Factory](buildcraft-7.0.20.jar) 
    UCHI    CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar) 
    UCHI    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHI    IC2{2.2.759-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.759-experimental.jar) 
    UCHI    Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40.jar) 
    UCHI    ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40.jar) 
    UCHI    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    UCHI    ComputerCraft{1.74} [ComputerCraft](ComputerCraft1.74.jar) 
    UCHI    MineFactoryReloaded{1.7.10R2.8.1B1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHI    EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    extracells{2.2.73} [Extra Cells 2](ExtraCells-1.7.10-2.2.73b129.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHI    ExtraUtilities{1.2.10} [Extra Utilities](extrautilities-1.2.10.jar) 
    UCHI    FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHI    Highlands{2.2.3} [Highlands](Highlands-1.7.2-v-2.2.3.jar) 
    UCHI    ImmersiveEngineering{0.5.2} [Immersive Engineering](ImmersiveEngineering-0.5.2.jar) 
    UCHI    immersiveintegration{0.4.2} [Immersive Integration](immersiveintegration-0.4.2.jar) 
    UCHI    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHI    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHI    MapWriter{2.1.4} [MapWriter](MapWriter-1.7.10-2.1.4.jar) 
    UCHI    ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHI    mo{0.4.0-RC2} [Matter Overdrive](MatterOverdrive-1.7.10-0.4.0-RC2.jar) 
    UCHI    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1B1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatAtum{1.7.10R2.8.1B1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1B1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1B1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1B1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1B1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatForestry{1.7.10R2.8.1B1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1B1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatIC2{1.7.10R2.8.1B1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.1B1} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHI    ProjRed|Core{4.7.0pre8.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
    UCHI    ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
    UCHI    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1B1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1B1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1B1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1B1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1B1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1B1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1B1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1B1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1B1-127.jar) 
    UCHI    NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHI    OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHI    OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHI    PowerConverters{1.7.10_3.3.0-jenkins.75} [Power Converters](PowerConverters-1.7.10_3.3.0-jenkins.75.jar) 
    UCHI    ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
    UCHI    ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
    UCHI    ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
    UCHI    ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
    UCHI    ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
    UCHI    ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
    UCHI    ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
    UCHI    techreborn{0.3.1.740} [TechReborn](TechReborn-0.3.1.740-universal.jar) 
    UCHI    ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHE    WarpDrive{1.3.2} [WarpDrive](warpdrive-1.3.2.jar) 
    UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHI    MCFrames{1.0} [MCFrames](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHI    RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UD  techrebornasm{000} [Techreborn-ASM](minecraft.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3496' Renderer: 'Intel(R) HD Graphics 4400'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.4B1-309
    MineFactoryReloaded: -[1.7.10]2.8.1B1-127
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3496, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

please don't ignore it it took a long time to write all the mods in the list and i really hope you can solve it because i love thath mod i follow it since the first version for 1.6.4

**Comment by LemADEC** [comment]
Thanks for your report. For the record, mod list and version are already given in the crash log you've provided.
You're crashing due to incompatibility with the Matter Overdrive mod, already reported as #39

**Comment by gunboy001** [comment]
thanks, and for the mod list yep I noticed it just when i pasted the crash log, my mistake
