### ISSUE TITLE
Pam's Harvestcraft Trees

### ISSUE THREAD

**Issue by LoriannBowman** [LemADEC/WarpDrive#533]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/8/22 10:21 AM
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: net/minecraftforge/common/BiomeDictionary
	at com.pam.pamhc2trees.init.TemperateFruitTreeWorldGenRegistry.addToBiome(TemperateFruitTreeWorldGenRegistry.java:19) ~[?:1.0.1] {re:classloading}
	at com.pam.pamhc2trees.SideProxy.onBiomeLoad(SideProxy.java:65) ~[?:1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:867) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$null$7(Biome.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.lambda$func_241797_a_$5(WorldSettingsImport.java:105) ~[?:?] {re:classloading}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(SourceFile:213) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(SourceFile:205) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(SourceFile:165) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:425) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3-forge-34.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.BiomeDictionary
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_202] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:105) ~[modlauncher-7.0.1.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202] {}
	... 60 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:272) ~[modlauncher-7.0.1.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) ~[modlauncher-7.0.1.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-7.0.1.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202] {}
		at com.pam.pamhc2trees.init.TemperateFruitTreeWorldGenRegistry.addToBiome(TemperateFruitTreeWorldGenRegistry.java:19) ~[?:1.0.1] {re:classloading}
		at com.pam.pamhc2trees.SideProxy.onBiomeLoad(SideProxy.java:65) ~[?:1.0.1] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:867) ~[?:?] {re:classloading}
		at net.minecraft.world.biome.Biome.lambda$null$7(Biome.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.WorldSettingsImport.lambda$func_241797_a_$5(WorldSettingsImport.java:105) ~[?:?] {re:classloading}
		at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
		at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
		at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.DynamicRegistries.func_243610_a(SourceFile:213) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.DynamicRegistries.func_243608_a(SourceFile:205) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?] {re:classloading}
		at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(SourceFile:165) ~[?:?] {re:classloading}
		at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
		at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:425) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
		at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
		at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
		at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
		at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
		at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3-forge-34.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0.jar:34.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.pam.pamhc2trees.init.TemperateFruitTreeWorldGenRegistry.addToBiome(TemperateFruitTreeWorldGenRegistry.java:19) ~[?:1.0.1] {re:classloading}
	at com.pam.pamhc2trees.SideProxy.onBiomeLoad(SideProxy.java:65) ~[?:1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:867) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$null$7(Biome.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.lambda$func_241797_a_$5(WorldSettingsImport.java:105) ~[?:?] {re:classloading}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(SourceFile:213) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(SourceFile:205) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(SourceFile:165) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.WorldSelectionScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:425) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3-forge-34.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 5.4.0-126-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1438284496 bytes (1371 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.0-client.jar Minecraft {minecraft@1.16.3 DONE}
		Useful-Backpacks-Mod-1.16.3 (1).jar Useful Backpacks {usefulbackpacks@1.11.5.82 DONE}
		U-Team-Core-1.16.3.jar U Team Core {uteamcore@3.1.9.181 DONE}
		pamhc2trees-1.16.3-1.0.1 (3).jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@1.0.1 DONE}
		BiomesOPlenty-1.16.3-12.0.0.400-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.400 DONE}
		mining-helmet-1.16.3-1.1.0.jar Mining Helmet {mining_helmet@1.1.0 DONE}
		Mermaid-Tail-Mod-1.16.3.jar Mermaid Tail Mod {mermaidtail@1.16.3-1.4.0 DONE}
		pamhc2crops-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Iron-Age-Furniture-Mod-1.16.3.jar Iron Age Furniture {ironagefurniture@1.16.3-0.1.0.4 DONE}
		jei-1.16.3-7.3.2.36.jar Just Enough Items {jei@7.3.2.29 DONE}
		Fairy-Lights-Mod-1.16.3.jar Fairy Lights {fairylights@4.0.0 DONE}
		pamhc2foodextended-1.16.3-1.0.2.jar Pam's HarvestCraft 2 Food Extended {pamhc2foodextended@version DONE}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 DONE}
		FastLeafDecay-Mod-1.16.3.jar FastLeafDecay {fastleafdecay@v25 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
	Launched Version: 1.16.3-forge-34.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 470.141.03, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sora_Shaders_1.11.zip
	OpenGlVersion: 4.6.0 NVIDIA 470.141.03
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by LemADEC** [comment]
This is the WarpDrive repository, we're not support Pam's Harvestcraft here...
