### ISSUE TITLE
Locks and WarpDrive incompatibility

### ISSUE THREAD

**Issue by CrafterDaemon** [LemADEC/WarpDrive#550]
Using both mods (Locks and WarpDrive) will cause the following messages to appear in the log for every registered block:
```
[19:31:33] [Client thread/ERROR]: Blacklisting block causing exception during dictionary checks minecraft:air Block{minecraft:air}, please report to mod author
[19:31:33] [Client thread/ERROR]: java.lang.NullPointerException
[19:31:33] [Client thread/ERROR]: 	at melonslise.locks.common.util.LocksUtil.intersecting(LocksUtil.java:93)
[19:31:33] [Client thread/ERROR]: 	at melonslise.locks.common.util.LocksUtil.intersecting(LocksUtil.java:88)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.block.Block.handler$zbo000$getExplosionResistance(Block.java:3217)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.block.Block.getExplosionResistance(Block.java:1523)
[19:31:33] [Client thread/ERROR]: 	at cr0s.warpdrive.config.Dictionary.adjustHardnessAndResistance(Dictionary.java:729)
[19:31:33] [Client thread/ERROR]: 	at cr0s.warpdrive.config.Dictionary.apply(Dictionary.java:660)
[19:31:33] [Client thread/ERROR]: 	at cr0s.warpdrive.config.WarpDriveConfig.onFMLPostInitialization(WarpDriveConfig.java:1775)
[19:31:33] [Client thread/ERROR]: 	at cr0s.warpdrive.WarpDrive.onFMLPostInitialization(WarpDrive.java:680)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:33] [Client thread/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:33] [Client thread/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:33] [Client thread/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:31:33] [Client thread/ERROR]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
[19:31:33] [Client thread/ERROR]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:33] [Client thread/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:33] [Client thread/ERROR]: 	at com.wildbamaboy.crashtomainmenu.asm.ASMHooks.onMinecraftRun(ASMHooks.java:37)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:33] [Client thread/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:33] [Client thread/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:31:33] [Client thread/ERROR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```
This can cause the output log to be extremely bloated, especially in larger modpacks. (Upon discovering this bug, my output logs were ~30 Megabytes uncompressed)
**To Reproduce**
1.  Run Minecraft with both Locks and WarpDrive installed
2.  Check Output Log
3.  See error

**Expected behavior**
Blocks to not be blacklisted

**Logs**
Log too long for Pastebin, added as attachment
[latest.log](https://github.com/LemADEC/WarpDrive/files/12643950/latest.log)

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.28
-   Forge version: 14.23.5.2860
-   Locks version: 3.0.0
-   Minecraft version: 1.12.2

**Additional context**
After launching only Locks and WarpDrive together and closing Minecraft after reaching the title screen, the latest.log file reached a size of 2.5 Megabytes...

**Comment by LemADEC** [comment]
It's an NPE in the Locks mod, should be fixed on their side.
That being said, locks won't transfer during jump, hence there's not much reasons to have both mods in the same pack and fix such issue.
