### ISSUE TITLE
Crash with ImmersiveEngineering 

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#88]
As reported by TheNextDecade here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2510855-1-6-4-1-7-10-warpdrive-build-your-ship-freely?page=6

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 05.09.15 17:06
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
at unwrittenfun.minecraft.immersiveintegration.tiles.TileMETransformer.removeCable(TileMETransformer.java:215)
at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.clearAllConnectionsFor(ImmersiveNetHandler.java:99)
at blusunrize.immersiveengineering.common.blocks.TileEntityImmersiveConnectable.func_145843_s(TileEntityImmersiveConnectable.java:41)
at unwrittenfun.minecraft.immersiveintegration.tiles.TileMETransformer.func_145843_s(TileMETransformer.java:173)
at net.minecraft.world.chunk.Chunk.func_150805_f(Chunk.java:901)
at net.minecraft.world.World.func_147475_p(World.java:2609)
at cr0s.warpdrive.EntityJump.moveShip(EntityJump.java:702)
```

>  My friend has a theory that the ME Transformer from Immersive Integration causes that crash. My theory is that IE wires cause that crash. But, well, transformers also use these wires. Anyway, my ship only has two ME Transformers, a single ME Wire connector, a bunch of LV Wire Connectors, and two of those breaker switches that disallow power to come through them when they're off. The report, from what I see, points at the ME Transformer.

**Comment by LemADEC** [comment]
87d4547230188479752f2fad5b963acfe2c2baa8 fixes IE wires, should help with that crash

**Comment by LemADEC** [comment]
Need to confirm if it's fixed

**Comment by LemADEC** [comment]
No news, assuming it's fixed
